// AI_GENERATED: Generated by AI (CLAUDE_CODE)
#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use crate::graph::property::constants::MAX_PROPERTY_RECORD_COUNT;
    use crate::graph::property::error::NexoraGraphPropertyError;
    use crate::graph::property::graph_property_store::PropertyStore;
    use crate::graph::record::types::PackedPtr;
    use crate::storage::page_store_disk::RegularPageStore;
    use crate::storage::storage_manager::StorageManager;

    fn tmp_path(name: &str) -> PathBuf {
        std::env::temp_dir().join(name)
    }

    fn cleanup(path: &PathBuf) {
        let _ = std::fs::remove_file(path);
    }

    // Test 1 — basic insert and get round trip
    #[test]
    fn test_insert_and_get_property() {
        let path = tmp_path("test_prop_insert_get.nxr");
        cleanup(&path);

        let store   = RegularPageStore::create(&path).unwrap();
        let mut mgr = StorageManager::from_page_store(store).unwrap();
        let mut ps  = PropertyStore::new(&mut mgr);

        let key   = PackedPtr::new(10, 0);
        let value = PackedPtr::new(11, 1);
        let ptr   = ps.insert(key, value).unwrap();

        let rec = ps.get(ptr).unwrap();
        assert_eq!(rec.key.page_id(),   10);
        assert_eq!(rec.value.page_id(), 11);
        assert!(rec.next.is_null());

        cleanup(&path);
    }

    // Test 2 — get after delete returns RecordNotFound
    #[test]
    fn test_get_deleted_property() {
        let path = tmp_path("test_prop_delete.nxr");
        cleanup(&path);

        let store   = RegularPageStore::create(&path).unwrap();
        let mut mgr = StorageManager::from_page_store(store).unwrap();
        let mut ps  = PropertyStore::new(&mut mgr);

        let ptr = ps.insert(PackedPtr::new(1, 0), PackedPtr::new(2, 0)).unwrap();
        ps.delete(ptr).unwrap();

        let result = ps.get(ptr);
        assert!(matches!(result, Err(NexoraGraphPropertyError::RecordNotFound)));

        cleanup(&path);
    }

    // Test 3 — slot reuse after delete
    #[test]
    fn test_slot_reuse_after_delete() {
        let path = tmp_path("test_prop_slot_reuse.nxr");
        cleanup(&path);

        let store   = RegularPageStore::create(&path).unwrap();
        let mut mgr = StorageManager::from_page_store(store).unwrap();
        let mut ps  = PropertyStore::new(&mut mgr);

        let ptr0 = ps.insert(PackedPtr::new(1, 0), PackedPtr::new(2, 0)).unwrap();
        let _    = ps.insert(PackedPtr::new(3, 0), PackedPtr::new(4, 0)).unwrap();

        ps.delete(ptr0).unwrap();

        let ptr_reused = ps.insert(PackedPtr::new(5, 0), PackedPtr::new(6, 0)).unwrap();
        assert_eq!(ptr_reused.slot(), ptr0.slot());
        assert_eq!(ptr_reused.page_id(), ptr0.page_id());

        cleanup(&path);
    }

    // Test 4 — insert multiple properties
    #[test]
    fn test_insert_multiple_properties() {
        let path = tmp_path("test_prop_multiple.nxr");
        cleanup(&path);

        let store   = RegularPageStore::create(&path).unwrap();
        let mut mgr = StorageManager::from_page_store(store).unwrap();
        let mut ps  = PropertyStore::new(&mut mgr);

        let mut ptrs = Vec::new();
        for i in 0..5u64 {
            let ptr = ps.insert(PackedPtr::new(i, 0), PackedPtr::new(i + 100, 0)).unwrap();
            ptrs.push((ptr, i));
        }

        for (ptr, i) in ptrs {
            let rec = ps.get(ptr).unwrap();
            assert_eq!(rec.key.page_id(), i);
            assert_eq!(rec.value.page_id(), i + 100);
        }

        cleanup(&path);
    }

    // Test 5 — filling a page causes a second page to be allocated
    #[test]
    fn test_property_page_overflow() {
        let path = tmp_path("test_prop_overflow.nxr");
        cleanup(&path);

        let store   = RegularPageStore::create(&path).unwrap();
        let mut mgr = StorageManager::from_page_store(store).unwrap();
        let mut ps  = PropertyStore::new(&mut mgr);

        let mut ptrs = Vec::new();
        for i in 0..=(MAX_PROPERTY_RECORD_COUNT as u64) {
            let ptr = ps.insert(PackedPtr::new(i, 0), PackedPtr::NULL).unwrap();
            ptrs.push(ptr);
        }

        let first_page = ptrs[0].page_id();
        let overflow   = ptrs[MAX_PROPERTY_RECORD_COUNT];
        assert_ne!(overflow.page_id(), first_page);

        cleanup(&path);
    }

    // Test 6 — properties survive a reopen
    #[test]
    fn test_property_persistence() {
        let path = tmp_path("test_prop_persistence.nxr");
        cleanup(&path);

        let ptr = {
            let store   = RegularPageStore::create(&path).unwrap();
            let mut mgr = StorageManager::from_page_store(store).unwrap();
            let ptr = {
                let mut ps = PropertyStore::new(&mut mgr);
                ps.insert(PackedPtr::new(42, 3), PackedPtr::new(99, 7)).unwrap()
            };
            mgr.close().unwrap();
            ptr
        };

        {
            let store   = RegularPageStore::open(&path).unwrap();
            let mut mgr = StorageManager::from_page_store(store).unwrap();
            let mut ps  = PropertyStore::new(&mut mgr);
            let rec = ps.get(ptr).unwrap();
            assert_eq!(rec.key.page_id(),   42);
            assert_eq!(rec.key.slot(),       3);
            assert_eq!(rec.value.page_id(), 99);
            assert_eq!(rec.value.slot(),     7);
        }

        cleanup(&path);
    }
}
