// AI_GENERATED: Generated by AI (CLAUDE_CODE)
#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use crate::graph::record::types::PackedPtr;
    use crate::graph::string::constants::{MAX_STRING_CHUNK_SIZE, MAX_STRING_LENGTH};
    use crate::graph::string::error::NexoraGraphStringError;
    use crate::graph::string::graph_string_store::StringStore;
    use crate::graph::string::page::GraphStringPage;
    use crate::storage::page_store_disk::RegularPageStore;
    use crate::storage::storage_manager::StorageManager;

    fn tmp_path(name: &str) -> PathBuf {
        std::env::temp_dir().join(name)
    }

    fn cleanup(path: &PathBuf) {
        let _ = std::fs::remove_file(path);
    }

    fn setup(path: &PathBuf) -> StorageManager<RegularPageStore> {
        let store = RegularPageStore::create(path).unwrap();
        StorageManager::from_page_store(store).unwrap()
    }

    // ── page-level tests ──────────────────────────────────────────────────────

    // Test 1 — insert_slot fields and data round-trip
    #[test]
    fn test_insert_slot_round_trip() {
        let mut page = GraphStringPage::init(10);
        let data = b"hello world";

        let slot_idx = page.insert_slot(data.len() as u16, data, PackedPtr::NULL).unwrap();
        let slot = page.get_slot(slot_idx).unwrap();

        assert_eq!(slot.total_length.get(), data.len() as u16);
        assert_eq!(slot.chunk_length.get(), data.len() as u16);
        assert!(slot.overflow_slot.is_null());

        let mut out = [0u8; 11];
        page.read_data(slot.offset.get(), slot.chunk_length.get(), &mut out).unwrap();
        assert_eq!(&out, data);
    }

    // Test 2 — get_slot out of bounds returns SlotNotFound
    #[test]
    fn test_get_slot_out_of_bounds() {
        let page = GraphStringPage::init(10);
        assert!(matches!(page.get_slot(0), Err(NexoraGraphStringError::SlotNotFound)));
    }

    // Test 3 — available_data decreases after each insert
    #[test]
    fn test_available_data_decreases() {
        let mut page = GraphStringPage::init(10);
        let before = page.available_data();

        page.insert_slot(5, b"hello", PackedPtr::NULL).unwrap();
        let after = page.available_data();

        assert!(after < before);
    }

    // Test 4 — has_space returns false when page cannot fit requested data
    #[test]
    fn test_has_space_false_when_full() {
        let mut page = GraphStringPage::init(10);
        let chunk = vec![0u8; 1000];

        // Each insert of 1000 bytes consumes ~1016 bytes (slot + data).
        // After 3 inserts ~3048 bytes used, leaving < 1000 bytes for data.
        for _ in 0..3 {
            page.insert_slot(1000, &chunk, PackedPtr::NULL).unwrap();
        }

        assert!(!page.has_space(1000));
    }

    // Test 5 — delete_slot clears the occupied bit
    #[test]
    fn test_delete_slot_clears_occupied() {
        let mut page = GraphStringPage::init(10);
        let idx = page.insert_slot(5, b"hello", PackedPtr::NULL).unwrap();

        assert!(page.string_page_header.occupied.is_set(idx));

        page.delete_slot(idx);
        assert!(!page.string_page_header.occupied.is_set(idx));
    }

    // ── store-level tests ─────────────────────────────────────────────────────

    // Test 6 — basic insert and get round-trip
    #[test]
    fn test_insert_and_get_short_string() {
        let path = tmp_path("test_str_insert_get.nxra");
        cleanup(&path);
        let mut manager = setup(&path);
        let mut store = StringStore::new(&mut manager);

        let data = b"hello nexora";
        let ptr = store.insert(data).unwrap();

        let mut out = [0u8; 12];
        let len = store.get(ptr, &mut out).unwrap();

        assert_eq!(len as usize, data.len());
        assert_eq!(&out[..len as usize], data);

        cleanup(&path);
    }

    // Test 7 — multiple strings on the same page
    #[test]
    fn test_insert_multiple_strings() {
        let path = tmp_path("test_str_multiple.nxra");
        cleanup(&path);
        let mut manager = setup(&path);
        let mut store = StringStore::new(&mut manager);

        let strings: &[&[u8]] = &[b"Person", b"KNOWS", b"age", b"name"];
        let ptrs: Vec<PackedPtr> = strings.iter()
            .map(|s| store.insert(s).unwrap())
            .collect();

        for (ptr, expected) in ptrs.iter().zip(strings.iter()) {
            let mut out = [0u8; 64];
            let len = store.get(*ptr, &mut out).unwrap();
            assert_eq!(&out[..len as usize], *expected);
        }

        cleanup(&path);
    }

    // Test 8 — string longer than MAX_STRING_CHUNK_SIZE spans multiple pages
    #[test]
    fn test_insert_overflow_string() {
        let path = tmp_path("test_str_overflow.nxra");
        cleanup(&path);
        let mut manager = setup(&path);
        let mut store = StringStore::new(&mut manager);

        let data: Vec<u8> = (0u8..=255).cycle().take(MAX_STRING_CHUNK_SIZE + 500).collect();
        let ptr = store.insert(&data).unwrap();

        let mut out = vec![0u8; data.len()];
        let len = store.get(ptr, &mut out).unwrap();

        assert_eq!(len as usize, data.len());
        assert_eq!(out, data);

        cleanup(&path);
    }

    // Test 9 — get with undersized buffer returns BufferTooSmall
    #[test]
    fn test_buffer_too_small() {
        let path = tmp_path("test_str_buf_small.nxra");
        cleanup(&path);
        let mut manager = setup(&path);
        let mut store = StringStore::new(&mut manager);

        let ptr = store.insert(b"hello world").unwrap();
        let mut out = [0u8; 4];

        assert!(matches!(store.get(ptr, &mut out), Err(NexoraGraphStringError::BufferTooSmall)));

        cleanup(&path);
    }

    // Test 10 — insert exceeding MAX_STRING_LENGTH returns StringTooLong
    #[test]
    fn test_string_too_long() {
        let path = tmp_path("test_str_too_long.nxra");
        cleanup(&path);
        let mut manager = setup(&path);
        let mut store = StringStore::new(&mut manager);

        let data = vec![0u8; MAX_STRING_LENGTH + 1];
        assert!(matches!(store.insert(&data), Err(NexoraGraphStringError::StringTooLong)));

        cleanup(&path);
    }

    // Test 11 — string survives close and reopen
    #[test]
    fn test_string_persistence() {
        let path = tmp_path("test_str_persistence.nxra");
        cleanup(&path);

        let ptr = {
            let mut manager = setup(&path);
            let ptr = {
                let mut store = StringStore::new(&mut manager);
                store.insert(b"persistent data").unwrap()
            };
            manager.close().unwrap();
            ptr
        };

        {
            let store = RegularPageStore::open(&path).unwrap();
            let mut manager = StorageManager::from_page_store(store).unwrap();
            let mut store = StringStore::new(&mut manager);

            let mut out = [0u8; 15];
            let len = store.get(ptr, &mut out).unwrap();
            assert_eq!(&out[..len as usize], b"persistent data");
        }

        cleanup(&path);
    }

    // Test 13 — delete frees all chunks in an overflow chain
    #[test]
    fn test_delete_string() {
        let path = tmp_path("test_str_delete.nxra");
        cleanup(&path);
        let mut manager = setup(&path);

        // Single-chunk string
        let ptr = {
            let mut store = StringStore::new(&mut manager);
            store.insert(b"hello").unwrap()
        };
        {
            let mut store = StringStore::new(&mut manager);
            store.delete(ptr).unwrap();
        }

        // Multi-chunk string — spans two pages
        let data: Vec<u8> = (0u8..=255).cycle().take(MAX_STRING_CHUNK_SIZE + 100).collect();
        let ptr2 = {
            let mut store = StringStore::new(&mut manager);
            store.insert(&data).unwrap()
        };
        {
            let mut store = StringStore::new(&mut manager);
            store.delete(ptr2).unwrap();
        }

        cleanup(&path);
    }

    // Test 12 — enough strings to fill one page, spill to a second
    #[test]
    fn test_page_overflow_to_new_page() {
        let path = tmp_path("test_str_page_overflow.nxra");
        cleanup(&path);
        let mut manager = setup(&path);
        let mut store = StringStore::new(&mut manager);

        // Each insert uses ~1016 bytes (1000 data + 16 slot).
        // ~4 inserts fills one page; the 5th goes to a new page.
        let data = vec![0xABu8; 1000];
        let ptrs: Vec<PackedPtr> = (0..5).map(|_| store.insert(&data).unwrap()).collect();

        for ptr in &ptrs {
            let mut out = vec![0u8; 1000];
            let len = store.get(*ptr, &mut out).unwrap();
            assert_eq!(len as usize, data.len());
            assert_eq!(out, data);
        }

        cleanup(&path);
    }
}
