// AI_GENERATED: Generated by AI (CLAUDE_CODE)
#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use crate::graph::node::constants::MAX_RECORD_COUNT;
    use crate::graph::node::error::NexoraGraphNodeError;
    use crate::graph::node::graph_node_store::GraphNodeStore;
    use crate::graph::record::types::{PackedPtr, Record};
    use crate::storage::page_store_disk::RegularPageStore;
    use crate::storage::storage_manager::StorageManager;

    fn tmp_path(name: &str) -> PathBuf {
        std::env::temp_dir().join(name)
    }

    fn cleanup(path: &PathBuf) {
        let _ = std::fs::remove_file(path);
    }

    // Test 1 — basic insert and get round trip
    #[test]
    fn test_insert_and_get_node() {
        let path = tmp_path("test_node_insert_get.nxra");
        cleanup(&path);

        let store = RegularPageStore::create(&path).unwrap();
        let mut manager = StorageManager::from_page_store(store).unwrap();
        let mut node_store = GraphNodeStore::new(&mut manager);

        let node_id = node_store.insert_node(1, PackedPtr::NULL).unwrap();
        let record = node_store.get_node(node_id).unwrap();

        assert_eq!(record.id(), node_id);

        cleanup(&path);
    }

    // Test 2 — get a node that was never inserted
    #[test]
    fn test_get_nonexistent_node() {
        let path = tmp_path("test_node_get_nonexistent.nxra");
        cleanup(&path);

        let store = RegularPageStore::create(&path).unwrap();
        let mut manager = StorageManager::from_page_store(store).unwrap();
        let mut node_store = GraphNodeStore::new(&mut manager);

        let result = node_store.get_node(999);
        assert!(matches!(result, Err(NexoraGraphNodeError::NodeNotFound)));

        cleanup(&path);
    }

    // Test 3 — delete a node, then get should return NodeNotFound
    #[test]
    fn test_delete_node() {
        let path = tmp_path("test_node_delete.nxra");
        cleanup(&path);

        let store = RegularPageStore::create(&path).unwrap();
        let mut manager = StorageManager::from_page_store(store).unwrap();
        let mut node_store = GraphNodeStore::new(&mut manager);

        let node_id = node_store.insert_node(1, PackedPtr::NULL).unwrap();
        node_store.delete_node(node_id).unwrap();

        assert!(matches!(node_store.get_node(node_id), Err(NexoraGraphNodeError::NodeNotFound)));

        cleanup(&path);
    }

    // Test 4 — delete a node that was never inserted
    #[test]
    fn test_delete_nonexistent_node() {
        let path = tmp_path("test_node_delete_nonexistent.nxra");
        cleanup(&path);

        let store = RegularPageStore::create(&path).unwrap();
        let mut manager = StorageManager::from_page_store(store).unwrap();
        let mut node_store = GraphNodeStore::new(&mut manager);

        let result = node_store.delete_node(999);
        assert!(matches!(result, Err(NexoraGraphNodeError::NodeNotFound)));

        cleanup(&path);
    }

    // Test 5 — insert multiple nodes, all are independently retrievable
    #[test]
    fn test_multiple_inserts() {
        let path = tmp_path("test_node_multiple_inserts.nxra");
        cleanup(&path);

        let store = RegularPageStore::create(&path).unwrap();
        let mut manager = StorageManager::from_page_store(store).unwrap();
        let mut node_store = GraphNodeStore::new(&mut manager);

        let ids: Vec<u64> = (0..10)
            .map(|i| node_store.insert_node(i as u32, PackedPtr::NULL).unwrap())
            .collect();

        for id in &ids {
            assert_eq!(node_store.get_node(*id).unwrap().id(), *id);
        }

        cleanup(&path);
    }

    // Test 6 — deleted slot is reused before growing the page
    #[test]
    fn test_slot_reuse_after_delete() {
        let path = tmp_path("test_node_slot_reuse.nxra");
        cleanup(&path);

        let store = RegularPageStore::create(&path).unwrap();
        let mut manager = StorageManager::from_page_store(store).unwrap();
        let mut node_store = GraphNodeStore::new(&mut manager);

        let id1 = node_store.insert_node(1, PackedPtr::NULL).unwrap();
        let id2 = node_store.insert_node(1, PackedPtr::NULL).unwrap();
        let id3 = node_store.insert_node(1, PackedPtr::NULL).unwrap();

        node_store.delete_node(id2).unwrap();
        let id4 = node_store.insert_node(1, PackedPtr::NULL).unwrap();

        node_store.get_node(id1).unwrap();
        node_store.get_node(id3).unwrap();
        node_store.get_node(id4).unwrap();
        assert!(matches!(node_store.get_node(id2), Err(NexoraGraphNodeError::NodeNotFound)));

        cleanup(&path);
    }

    // Test 7 — inserting beyond MAX_RECORD_COUNT triggers new page allocation
    #[test]
    fn test_page_overflow() {
        let path = tmp_path("test_node_page_overflow.nxra");
        cleanup(&path);

        let store = RegularPageStore::create(&path).unwrap();
        let mut manager = StorageManager::from_page_store(store).unwrap();
        let mut node_store = GraphNodeStore::new(&mut manager);

        let ids: Vec<u64> = (0..MAX_RECORD_COUNT + 5)
            .map(|_| node_store.insert_node(1, PackedPtr::NULL).unwrap())
            .collect();

        for id in &ids {
            assert_eq!(node_store.get_node(*id).unwrap().id(), *id);
        }

        cleanup(&path);
    }

    // Test 8 — footer node_count stays accurate across inserts and deletes
    #[test]
    fn test_node_count_tracking() {
        let path = tmp_path("test_node_count_tracking.nxra");
        cleanup(&path);

        let store = RegularPageStore::create(&path).unwrap();
        let mut manager = StorageManager::from_page_store(store).unwrap();

        let id_to_delete = {
            let mut node_store = GraphNodeStore::new(&mut manager);
            node_store.insert_node(1, PackedPtr::NULL).unwrap();
            node_store.insert_node(1, PackedPtr::NULL).unwrap();
            node_store.insert_node(1, PackedPtr::NULL).unwrap()
        };

        assert_eq!(manager.footer.node_count.get(), 3);

        {
            let mut node_store = GraphNodeStore::new(&mut manager);
            node_store.delete_node(id_to_delete).unwrap();
        }

        assert_eq!(manager.footer.node_count.get(), 2);

        cleanup(&path);
    }

    // Test 9 — nodes survive close and reopen
    #[test]
    fn test_node_persistence() {
        let path = tmp_path("test_node_persistence.nxra");
        cleanup(&path);

        let node_id = {
            let store = RegularPageStore::create(&path).unwrap();
            let mut manager = StorageManager::from_page_store(store).unwrap();
            let id = {
                let mut node_store = GraphNodeStore::new(&mut manager);
                node_store.insert_node(1, PackedPtr::NULL).unwrap()
            };
            manager.close().unwrap();
            id
        };

        {
            let store = RegularPageStore::open(&path).unwrap();
            let mut manager = StorageManager::from_page_store(store).unwrap();
            let mut node_store = GraphNodeStore::new(&mut manager);
            let record = node_store.get_node(node_id).unwrap();
            assert_eq!(record.id(), node_id);
        }

        cleanup(&path);
    }

    // Test 10 — delete all nodes on a page, then insert again
    #[test]
    fn test_delete_all_then_insert() {
        let path = tmp_path("test_node_delete_all_insert.nxra");
        cleanup(&path);

        let store = RegularPageStore::create(&path).unwrap();
        let mut manager = StorageManager::from_page_store(store).unwrap();
        let mut node_store = GraphNodeStore::new(&mut manager);

        let ids: Vec<u64> = (0..5)
            .map(|_| node_store.insert_node(1, PackedPtr::NULL).unwrap())
            .collect();

        for id in &ids {
            node_store.delete_node(*id).unwrap();
        }

        drop(node_store);
        assert_eq!(manager.footer.node_count.get(), 0);

        cleanup(&path);
    }
}
