// AI_GENERATED: Generated by AI (CLAUDE_CODE)
use std::cell::RefCell;
use std::rc::Rc;

use crate::graph::graphstore::graphstore::GraphStore;
use crate::graph::record::types::RecordCursor;
use crate::storage::page_store_disk::RegularPageStore;

pub struct LuaGraphStore(pub Rc<RefCell<GraphStore<RegularPageStore>>>);

pub struct LuaCursor(pub RecordCursor);

#[cfg(feature = "lua")]
impl mlua::UserData for LuaCursor {}

#[cfg(feature = "lua")]
impl mlua::UserData for LuaGraphStore {
    fn add_methods<M: mlua::UserDataMethods<Self>>(methods: &mut M) {
        // --- Nodes ---

        methods.add_method_mut("insert_node", |_, this, label: String| {
            this.0.borrow_mut().insert_node(&label).map_err(mlua::Error::external)
        });

        methods.add_method_mut("get_node", |lua, this, id: u64| {
            let node = this.0.borrow_mut().get_node(id).map_err(mlua::Error::external)?;
            let t = lua.create_table()?;
            t.set("id", node.id)?;
            t.set("label", node.label)?;
            Ok(t)
        });

        methods.add_method_mut("update_node", |_, this, (id, label): (u64, String)| {
            use crate::graph::models::Node;
            let node = Node { id, label };
            this.0.borrow_mut().update_node(&node).map_err(mlua::Error::external)
        });

        methods.add_method_mut("delete_node", |_, this, id: u64| {
            this.0.borrow_mut().delete_node(id).map_err(mlua::Error::external)
        });

        // --- Edges ---

        methods.add_method_mut("insert_edge", |_, this, (src, dst, label, weight): (u64, u64, String, f64)| {
            this.0.borrow_mut().insert_edge(src, dst, &label, weight).map_err(mlua::Error::external)
        });

        methods.add_method_mut("get_edge", |lua, this, id: u64| {
            let edge = this.0.borrow_mut().get_edge(id).map_err(mlua::Error::external)?;
            let t = lua.create_table()?;
            t.set("id", edge.id)?;
            t.set("src", edge.src)?;
            t.set("dst", edge.dst)?;
            t.set("label", edge.label)?;
            t.set("weight", edge.weight)?;
            Ok(t)
        });

        methods.add_method_mut("update_edge", |_, this, (id, label, weight): (u64, String, f64)| {
            use crate::graph::models::Edge;
            let existing = this.0.borrow_mut().get_edge(id).map_err(mlua::Error::external)?;
            let edge = Edge { id, src: existing.src, dst: existing.dst, label, weight };
            this.0.borrow_mut().update_edge(&edge).map_err(mlua::Error::external)
        });

        methods.add_method_mut("delete_edge", |_, this, id: u64| {
            this.0.borrow_mut().delete_edge(id).map_err(mlua::Error::external)
        });

        // --- Traversal ---

        methods.add_method_mut("outgoing_cursor", |_, this, node_id: u64| {
            let cursor = this.0.borrow_mut().outgoing_cursor(node_id).map_err(mlua::Error::external)?;
            Ok(LuaCursor(cursor))
        });

        methods.add_method_mut("incoming_cursor", |_, this, node_id: u64| {
            let cursor = this.0.borrow_mut().incoming_cursor(node_id).map_err(mlua::Error::external)?;
            Ok(LuaCursor(cursor))
        });

        methods.add_method_mut("next_outgoing", |lua, this, cursor: mlua::AnyUserData| {
            let mut lc = cursor.borrow_mut::<LuaCursor>()?;
            let edge = this.0.borrow_mut().next_outgoing(&mut lc.0).map_err(mlua::Error::external)?;
            edge_to_lua(lua, edge)
        });

        methods.add_method_mut("next_incoming", |lua, this, cursor: mlua::AnyUserData| {
            let mut lc = cursor.borrow_mut::<LuaCursor>()?;
            let edge = this.0.borrow_mut().next_incoming(&mut lc.0).map_err(mlua::Error::external)?;
            edge_to_lua(lua, edge)
        });

        // --- Scan ---

        methods.add_method_mut("all_nodes_cursor", |_, this, ()| {
            let cursor = this.0.borrow_mut().all_nodes_cursor().map_err(mlua::Error::external)?;
            Ok(LuaCursor(cursor))
        });

        methods.add_method_mut("all_edges_cursor", |_, this, ()| {
            let cursor = this.0.borrow_mut().all_edges_cursor().map_err(mlua::Error::external)?;
            Ok(LuaCursor(cursor))
        });

        methods.add_method_mut("next_node", |lua, this, cursor: mlua::AnyUserData| {
            let mut lc = cursor.borrow_mut::<LuaCursor>()?;
            let node = this.0.borrow_mut().next_node(&mut lc.0).map_err(mlua::Error::external)?;
            match node {
                None => Ok(mlua::Value::Nil),
                Some(n) => {
                    let t = lua.create_table()?;
                    t.set("id", n.id)?;
                    t.set("label", n.label)?;
                    Ok(mlua::Value::Table(t))
                }
            }
        });

        methods.add_method_mut("next_edge", |lua, this, cursor: mlua::AnyUserData| {
            let mut lc = cursor.borrow_mut::<LuaCursor>()?;
            let edge = this.0.borrow_mut().next_edge(&mut lc.0).map_err(mlua::Error::external)?;
            edge_to_lua(lua, edge)
        });

        // --- Node properties ---

        methods.add_method_mut("set_node_property", |_, this, (node_id, key, value): (u64, String, String)| {
            this.0.borrow_mut().set_node_property(node_id, &key, &value).map_err(mlua::Error::external)
        });

        methods.add_method_mut("get_node_property", |_, this, (node_id, key): (u64, String)| {
            let mut buf = vec![0u8; crate::graph::string::constants::MAX_STRING_LENGTH];
            let result = this.0.borrow_mut().get_node_property(node_id, &key, &mut buf).map_err(mlua::Error::external)?;
            Ok(result.map(|len| String::from_utf8_lossy(&buf[..len as usize]).into_owned()))
        });

        methods.add_method_mut("delete_node_property", |_, this, (node_id, key): (u64, String)| {
            this.0.borrow_mut().delete_node_property(node_id, &key).map_err(mlua::Error::external)
        });

        // --- Edge properties ---

        methods.add_method_mut("set_edge_property", |_, this, (edge_id, key, value): (u64, String, String)| {
            this.0.borrow_mut().set_edge_property(edge_id, &key, &value).map_err(mlua::Error::external)
        });

        methods.add_method_mut("get_edge_property", |_, this, (edge_id, key): (u64, String)| {
            let mut buf = vec![0u8; crate::graph::string::constants::MAX_STRING_LENGTH];
            let result = this.0.borrow_mut().get_edge_property(edge_id, &key, &mut buf).map_err(mlua::Error::external)?;
            Ok(result.map(|len| String::from_utf8_lossy(&buf[..len as usize]).into_owned()))
        });

        methods.add_method_mut("delete_edge_property", |_, this, (edge_id, key): (u64, String)| {
            this.0.borrow_mut().delete_edge_property(edge_id, &key).map_err(mlua::Error::external)
        });

        // --- Property iteration ---

        methods.add_method_mut("node_properties_cursor", |_, this, node_id: u64| {
            let cursor = this.0.borrow_mut().node_properties_cursor(node_id).map_err(mlua::Error::external)?;
            Ok(LuaCursor(cursor))
        });

        methods.add_method_mut("edge_properties_cursor", |_, this, edge_id: u64| {
            let cursor = this.0.borrow_mut().edge_properties_cursor(edge_id).map_err(mlua::Error::external)?;
            Ok(LuaCursor(cursor))
        });

        methods.add_method_mut("next_property", |lua, this, cursor: mlua::AnyUserData| {
            let mut lc = cursor.borrow_mut::<LuaCursor>()?;
            let prop = this.0.borrow_mut().next_property(&mut lc.0).map_err(mlua::Error::external)?;
            match prop {
                None => Ok(mlua::Value::Nil),
                Some(p) => {
                    let t = lua.create_table()?;
                    t.set("key", p.key)?;
                    t.set("value", p.value)?;
                    Ok(mlua::Value::Table(t))
                }
            }
        });
    }
}

#[cfg(feature = "lua")]
fn edge_to_lua(lua: &mlua::Lua, edge: Option<crate::graph::models::Edge>) -> mlua::Result<mlua::Value> {
    match edge {
        None => Ok(mlua::Value::Nil),
        Some(e) => {
            let t = lua.create_table()?;
            t.set("id", e.id)?;
            t.set("src", e.src)?;
            t.set("dst", e.dst)?;
            t.set("label", e.label)?;
            t.set("weight", e.weight)?;
            Ok(mlua::Value::Table(t))
        }
    }
}
