// AI_GENERATED: Generated by AI (CLAUDE_CODE)
use std::cell::RefCell;
use std::collections::{HashSet, VecDeque};
use std::rc::Rc;

use crate::graph::graphstore::graphstore::GraphStore;
use crate::graph::record::types::RecordCursor;
use crate::storage::page_store::PageStore;
use crate::storage::page_store_disk::RegularPageStore;
use crate::storage::wal::WALPageStore;

pub type LuaStore = GraphStore<WALPageStore<RegularPageStore>>;
pub struct LuaGraphStore<S: PageStore>(pub Rc<RefCell<GraphStore<S>>>);

pub struct LuaCursor(pub RecordCursor);

#[cfg(feature = "lua")]
impl mlua::UserData for LuaCursor {}

#[cfg(feature = "lua")]
impl<S: PageStore + 'static> mlua::UserData for LuaGraphStore<S> {
    fn add_methods<M: mlua::UserDataMethods<Self>>(methods: &mut M) {
        // --- Nodes ---

        methods.add_method("insert_node", |_, this, label: String| {
            this.0.borrow_mut().insert_node(&label).map_err(mlua::Error::external)
        });

        methods.add_method("get_node", |lua, this, id: u64| {
            let node = this.0.borrow_mut().get_node(id).map_err(mlua::Error::external)?;
            let t = lua.create_table()?;
            t.set("id", node.id)?;
            t.set("label", node.label)?;
            Ok(t)
        });

        methods.add_method("update_node", |_, this, (id, label): (u64, String)| {
            use crate::graph::models::Node;
            let node = Node { id, label };
            this.0.borrow_mut().update_node(&node).map_err(mlua::Error::external)
        });

        methods.add_method("delete_node", |_, this, id: u64| {
            this.0.borrow_mut().delete_node(id).map_err(mlua::Error::external)
        });

        // --- Edges ---

        methods.add_method("insert_edge", |_, this, (src, dst, label, weight): (u64, u64, String, f64)| {
            this.0.borrow_mut().insert_edge(src, dst, &label, weight).map_err(mlua::Error::external)
        });

        methods.add_method("get_edge", |lua, this, id: u64| {
            let edge = this.0.borrow_mut().get_edge(id).map_err(mlua::Error::external)?;
            let t = lua.create_table()?;
            t.set("id", edge.id)?;
            t.set("src", edge.src)?;
            t.set("dst", edge.dst)?;
            t.set("label", edge.label)?;
            t.set("weight", edge.weight)?;
            Ok(t)
        });

        methods.add_method("update_edge", |_, this, (id, label, weight): (u64, String, f64)| {
            use crate::graph::models::Edge;
            let existing = this.0.borrow_mut().get_edge(id).map_err(mlua::Error::external)?;
            let edge = Edge { id, src: existing.src, dst: existing.dst, label, weight };
            this.0.borrow_mut().update_edge(&edge).map_err(mlua::Error::external)
        });

        methods.add_method("delete_edge", |_, this, id: u64| {
            this.0.borrow_mut().delete_edge(id).map_err(mlua::Error::external)
        });

        // --- Traversal ---

        methods.add_method("outgoing_cursor", |_, this, node_id: u64| {
            let cursor = this.0.borrow_mut().outgoing_cursor(node_id).map_err(mlua::Error::external)?;
            Ok(LuaCursor(cursor))
        });

        methods.add_method("incoming_cursor", |_, this, node_id: u64| {
            let cursor = this.0.borrow_mut().incoming_cursor(node_id).map_err(mlua::Error::external)?;
            Ok(LuaCursor(cursor))
        });

        methods.add_method("next_outgoing", |lua, this, cursor: mlua::AnyUserData| {
            let mut lc = cursor.borrow_mut::<LuaCursor>()?;
            let edge = this.0.borrow_mut().next_outgoing(&mut lc.0).map_err(mlua::Error::external)?;
            edge_to_lua(lua, edge)
        });

        methods.add_method("next_incoming", |lua, this, cursor: mlua::AnyUserData| {
            let mut lc = cursor.borrow_mut::<LuaCursor>()?;
            let edge = this.0.borrow_mut().next_incoming(&mut lc.0).map_err(mlua::Error::external)?;
            edge_to_lua(lua, edge)
        });

        // --- Scan ---

        methods.add_method("all_nodes_cursor", |_, this, ()| {
            let cursor = this.0.borrow_mut().all_nodes_cursor().map_err(mlua::Error::external)?;
            Ok(LuaCursor(cursor))
        });

        methods.add_method("all_edges_cursor", |_, this, ()| {
            let cursor = this.0.borrow_mut().all_edges_cursor().map_err(mlua::Error::external)?;
            Ok(LuaCursor(cursor))
        });

        methods.add_method("next_node", |lua, this, cursor: mlua::AnyUserData| {
            let mut lc = cursor.borrow_mut::<LuaCursor>()?;
            let node = this.0.borrow_mut().next_node(&mut lc.0).map_err(mlua::Error::external)?;
            match node {
                None => Ok(mlua::Value::Nil),
                Some(n) => {
                    let t = lua.create_table()?;
                    t.set("id", n.id)?;
                    t.set("label", n.label)?;
                    Ok(mlua::Value::Table(t))
                }
            }
        });

        methods.add_method("next_edge", |lua, this, cursor: mlua::AnyUserData| {
            let mut lc = cursor.borrow_mut::<LuaCursor>()?;
            let edge = this.0.borrow_mut().next_edge(&mut lc.0).map_err(mlua::Error::external)?;
            edge_to_lua(lua, edge)
        });

        // --- Node properties ---

        methods.add_method("set_node_property", |_, this, (node_id, key, value): (u64, String, String)| {
            this.0.borrow_mut().set_node_property(node_id, &key, &value).map_err(mlua::Error::external)
        });

        methods.add_method("get_node_property", |_, this, (node_id, key): (u64, String)| {
            let mut buf = vec![0u8; crate::graph::string::constants::MAX_STRING_LENGTH];
            let result = this.0.borrow_mut().get_node_property(node_id, &key, &mut buf).map_err(mlua::Error::external)?;
            Ok(result.map(|len| String::from_utf8_lossy(&buf[..len as usize]).into_owned()))
        });

        methods.add_method("delete_node_property", |_, this, (node_id, key): (u64, String)| {
            this.0.borrow_mut().delete_node_property(node_id, &key).map_err(mlua::Error::external)
        });

        // --- Edge properties ---

        methods.add_method("set_edge_property", |_, this, (edge_id, key, value): (u64, String, String)| {
            this.0.borrow_mut().set_edge_property(edge_id, &key, &value).map_err(mlua::Error::external)
        });

        methods.add_method("get_edge_property", |_, this, (edge_id, key): (u64, String)| {
            let mut buf = vec![0u8; crate::graph::string::constants::MAX_STRING_LENGTH];
            let result = this.0.borrow_mut().get_edge_property(edge_id, &key, &mut buf).map_err(mlua::Error::external)?;
            Ok(result.map(|len| String::from_utf8_lossy(&buf[..len as usize]).into_owned()))
        });

        methods.add_method("delete_edge_property", |_, this, (edge_id, key): (u64, String)| {
            this.0.borrow_mut().delete_edge_property(edge_id, &key).map_err(mlua::Error::external)
        });

        // --- High-level traversal ---

        // for_each_outgoing(node_id, fn(edge)) — callback receives an edge table.
        // Return false from the callback to stop early.
        methods.add_method("for_each_outgoing", |lua, this, (node_id, f): (u64, mlua::Function)| {
            let mut cursor = this.0.borrow_mut().outgoing_cursor(node_id).map_err(mlua::Error::external)?;
            loop {
                let edge = this.0.borrow_mut().next_outgoing(&mut cursor).map_err(mlua::Error::external)?;
                match edge {
                    None => break,
                    Some(e) => {
                        let t = make_edge_table(lua, &e)?;
                        let cont: mlua::Value = f.call(t)?;
                        if matches!(cont, mlua::Value::Boolean(false)) {
                            break;
                        }
                    }
                }
            }
            Ok(())
        });

        // for_each_incoming(node_id, fn(edge))
        methods.add_method("for_each_incoming", |lua, this, (node_id, f): (u64, mlua::Function)| {
            let mut cursor = this.0.borrow_mut().incoming_cursor(node_id).map_err(mlua::Error::external)?;
            loop {
                let edge = this.0.borrow_mut().next_incoming(&mut cursor).map_err(mlua::Error::external)?;
                match edge {
                    None => break,
                    Some(e) => {
                        let t = make_edge_table(lua, &e)?;
                        let cont: mlua::Value = f.call(t)?;
                        if matches!(cont, mlua::Value::Boolean(false)) {
                            break;
                        }
                    }
                }
            }
            Ok(())
        });

        // bfs(start, max_depth, fn(node, depth)) — callback receives a node table and integer depth.
        // Return false to stop early.
        methods.add_method("bfs", |lua, this, (start, max_depth, f): (u64, usize, mlua::Function)| {
            let mut visited: HashSet<u64> = HashSet::new();
            let mut queue: VecDeque<(u64, usize)> = VecDeque::new();
            visited.insert(start);
            queue.push_back((start, 0));

            while let Some((node_id, depth)) = queue.pop_front() {
                let node = this.0.borrow_mut().get_node(node_id).map_err(mlua::Error::external)?;
                let t = make_node_table(lua, &node)?;
                let cont: mlua::Value = f.call((t, depth))?;
                if matches!(cont, mlua::Value::Boolean(false)) {
                    break;
                }
                if depth < max_depth {
                    let mut cursor = this.0.borrow_mut().outgoing_cursor(node_id).map_err(mlua::Error::external)?;
                    loop {
                        let edge = this.0.borrow_mut().next_outgoing(&mut cursor).map_err(mlua::Error::external)?;
                        match edge {
                            None => break,
                            Some(e) => {
                                if visited.insert(e.dst) {
                                    queue.push_back((e.dst, depth + 1));
                                }
                            }
                        }
                    }
                }
            }
            Ok(())
        });

        // dfs(start, max_depth, fn(node, depth))
        methods.add_method("dfs", |lua, this, (start, max_depth, f): (u64, usize, mlua::Function)| {
            let mut visited: HashSet<u64> = HashSet::new();
            let mut stack: Vec<(u64, usize)> = vec![(start, 0)];

            while let Some((node_id, depth)) = stack.pop() {
                if !visited.insert(node_id) {
                    continue;
                }
                let node = this.0.borrow_mut().get_node(node_id).map_err(mlua::Error::external)?;
                let t = make_node_table(lua, &node)?;
                let cont: mlua::Value = f.call((t, depth))?;
                if matches!(cont, mlua::Value::Boolean(false)) {
                    break;
                }
                if depth < max_depth {
                    let mut cursor = this.0.borrow_mut().outgoing_cursor(node_id).map_err(mlua::Error::external)?;
                    let mut neighbors: Vec<u64> = Vec::new();
                    loop {
                        let edge = this.0.borrow_mut().next_outgoing(&mut cursor).map_err(mlua::Error::external)?;
                        match edge {
                            None => break,
                            Some(e) => {
                                if !visited.contains(&e.dst) {
                                    neighbors.push(e.dst);
                                }
                            }
                        }
                    }
                    for neighbor in neighbors.into_iter().rev() {
                        stack.push((neighbor, depth + 1));
                    }
                }
            }
            Ok(())
        });

        // has_path(src, dst) → boolean
        methods.add_method("has_path", |_, this, (src, dst): (u64, u64)| {
            use crate::api::traversal::{Traversal, TraverseApi};
            let mut gs = this.0.borrow_mut();
            Traversal::new(&mut *gs).has_path(src, dst).map_err(mlua::Error::external)
        });

        // shortest_path(src, dst) → table (array of node ids) | nil
        methods.add_method("shortest_path", |lua, this, (src, dst): (u64, u64)| {
            use crate::api::traversal::{Traversal, TraverseApi};
            let path = {
                let mut gs = this.0.borrow_mut();
                Traversal::new(&mut *gs).shortest_path(src, dst).map_err(mlua::Error::external)?
            };
            match path {
                None => Ok(mlua::Value::Nil),
                Some(ids) => {
                    let t = lua.create_table()?;
                    for (i, id) in ids.iter().enumerate() {
                        t.set(i + 1, *id)?;
                    }
                    Ok(mlua::Value::Table(t))
                }
            }
        });

        // for_each_with_label(label, fn(node)) — visits every node whose label matches.
        // Return false from the callback to stop early.
        methods.add_method("for_each_with_label", |lua, this, (label, f): (String, mlua::Function)| {
            let mut cursor = this.0.borrow_mut().all_nodes_cursor().map_err(mlua::Error::external)?;
            loop {
                let node = this.0.borrow_mut().next_node(&mut cursor).map_err(mlua::Error::external)?;
                match node {
                    None => break,
                    Some(n) if n.label == label => {
                        let t = make_node_table(lua, &n)?;
                        let cont: mlua::Value = f.call(t)?;
                        if matches!(cont, mlua::Value::Boolean(false)) {
                            break;
                        }
                    }
                    Some(_) => {}
                }
            }
            Ok(())
        });

        // --- Property iteration ---

        methods.add_method("node_properties_cursor", |_, this, node_id: u64| {
            let cursor = this.0.borrow_mut().node_properties_cursor(node_id).map_err(mlua::Error::external)?;
            Ok(LuaCursor(cursor))
        });

        methods.add_method("edge_properties_cursor", |_, this, edge_id: u64| {
            let cursor = this.0.borrow_mut().edge_properties_cursor(edge_id).map_err(mlua::Error::external)?;
            Ok(LuaCursor(cursor))
        });

        methods.add_method("next_property", |lua, this, cursor: mlua::AnyUserData| {
            let mut lc = cursor.borrow_mut::<LuaCursor>()?;
            let prop = this.0.borrow_mut().next_property(&mut lc.0).map_err(mlua::Error::external)?;
            match prop {
                None => Ok(mlua::Value::Nil),
                Some(p) => {
                    let t = lua.create_table()?;
                    t.set("key", p.key)?;
                    t.set("value", p.value)?;
                    Ok(mlua::Value::Table(t))
                }
            }
        });
    }
}

#[cfg(feature = "lua")]
fn make_node_table(lua: &mlua::Lua, node: &crate::graph::models::Node) -> mlua::Result<mlua::Table> {
    let t = lua.create_table()?;
    t.set("id", node.id)?;
    t.set("label", node.label.clone())?;
    Ok(t)
}

#[cfg(feature = "lua")]
fn make_edge_table(lua: &mlua::Lua, edge: &crate::graph::models::Edge) -> mlua::Result<mlua::Table> {
    let t = lua.create_table()?;
    t.set("id", edge.id)?;
    t.set("src", edge.src)?;
    t.set("dst", edge.dst)?;
    t.set("label", edge.label.clone())?;
    t.set("weight", edge.weight)?;
    Ok(t)
}

#[cfg(feature = "lua")]
fn edge_to_lua(lua: &mlua::Lua, edge: Option<crate::graph::models::Edge>) -> mlua::Result<mlua::Value> {
    match edge {
        None => Ok(mlua::Value::Nil),
        Some(e) => Ok(mlua::Value::Table(make_edge_table(lua, &e)?)),
    }
}
