// AI_GENERATED: Generated by AI (CLAUDE_CODE)
use std::cell::RefCell;
use std::path::Path;
use std::rc::Rc;

use mlua::Lua;
use rustyline::DefaultEditor;
use rustyline::error::ReadlineError;

use crate::graph::graphstore::graphstore::GraphStore;
use crate::lua::graph_store::LuaGraphStore;

pub enum OpenMode {
    /// Open if exists, create if not.
    Auto,
    /// Always create — return an error if the file already exists.
    ForceNew,
}

pub fn run(path: &Path, mode: OpenMode) -> Result<(), Box<dyn std::error::Error>> {
    let (store, created) = match mode {
        OpenMode::ForceNew => {
            if path.exists() {
                return Err(format!("'{}' already exists (omit --new to open it)", path.display()).into());
            }
            (GraphStore::create(path)?, true)
        }
        OpenMode::Auto => {
            if path.exists() {
                (GraphStore::open(path)?, false)
            } else {
                (GraphStore::create(path)?, true)
            }
        }
    };

    let shared = Rc::new(RefCell::new(store));
    let lua = Lua::new();
    lua.globals().set("db", LuaGraphStore(Rc::clone(&shared)))?;

    // Persistent environment — variable assignments survive between lines.
    let env: mlua::Table = lua
        .load("return setmetatable({}, {__index = _G, __newindex = function(t,k,v) rawset(t,k,v) end})")
        .eval()?;

    // Pre-load a help() function into the session env.
    lua.load(r#"
        function help()
            print([[
Nodes
  db:insert_node(label)                    → id
  db:get_node(id)                          → {id, label}
  db:update_node(id, label)
  db:delete_node(id)

Edges
  db:insert_edge(src, dst, label, weight)  → id
  db:get_edge(id)                          → {id, src, dst, label, weight}
  db:update_edge(id, label, weight)
  db:delete_edge(id)

Properties
  db:set_node_property(id, key, value)
  db:get_node_property(id, key)            → value or nil
  db:delete_node_property(id, key)         → bool
  db:set_edge_property(id, key, value)
  db:get_edge_property(id, key)            → value or nil
  db:delete_edge_property(id, key)         → bool

Traversal
  db:outgoing_cursor(node_id)              → cursor
  db:incoming_cursor(node_id)              → cursor
  db:next_outgoing(cursor)                 → edge or nil
  db:next_incoming(cursor)                 → edge or nil

Scan
  db:all_nodes_cursor()                    → cursor
  db:all_edges_cursor()                    → cursor
  db:next_node(cursor)                     → node or nil
  db:next_edge(cursor)                     → edge or nil

Property iteration
  db:node_properties_cursor(node_id)       → cursor
  db:edge_properties_cursor(edge_id)       → cursor
  db:next_property(cursor)                 → {key, value} or nil
]])
        end
    "#).exec()?;
    lua.globals().get::<mlua::Function>("load")
        .ok(); // ignore — just warming the env

    // Copy help into the persistent env so it's accessible.
    let help_fn: mlua::Value = lua.globals().get("help")?;
    env.set("help", help_fn)?;

    print_banner(path, created);

    let mut rl = DefaultEditor::new()?;
    let mut pending = String::new();

    loop {
        let prompt = if pending.is_empty() { "nexora> " } else { "  ...  > " };
        match rl.readline(prompt) {
            Ok(line) => {
                pending.push_str(&line);
                pending.push('\n');

                let code = strip_local(&pending);

                // Try as expression first so bare values print automatically.
                let expr = format!("return {}", code.trim_end());
                if let Ok(vals) = lua.load(&expr).set_environment(env.clone()).eval::<mlua::MultiValue>() {
                    let _ = rl.add_history_entry(pending.trim());
                    pending.clear();
                    let parts: Vec<String> = vals.iter().map(lua_display).collect();
                    if !parts.is_empty() { println!("{}", parts.join("\t")); }
                    continue;
                }

                match lua.load(&code).set_environment(env.clone()).exec() {
                    Ok(_) => {
                        let _ = rl.add_history_entry(pending.trim());
                        pending.clear();
                    }
                    Err(mlua::Error::SyntaxError { incomplete_input: true, .. }) => {}
                    Err(e) => {
                        eprintln!("error: {e}");
                        pending.clear();
                    }
                }
            }
            Err(ReadlineError::Interrupted) => {
                pending.clear();
                println!("(interrupted — Ctrl-D to quit)");
            }
            Err(_) => break,
        }
    }

    shared.borrow_mut().close()?;
    println!("\nBye.");
    Ok(())
}

fn print_banner(path: &Path, created: bool) {
    let status = if created { "created" } else { "opened" };
    let db_str = path.display().to_string();
    println!();
    println!("  Nexora {}  —  embedded graph database", env!("CARGO_PKG_VERSION"));
    println!("  ─────────────────────────────────────────");
    println!("  db      {}  [{}]", db_str, status);
    println!("  engine  Lua 5.4");
    println!("  hint    type help() for API reference, Ctrl-D to quit");
    println!();
}

fn strip_local(code: &str) -> String {
    let trimmed = code.trim();
    let lines: Vec<&str> = trimmed.lines().collect();
    if lines.len() == 1 && trimmed.starts_with("local ") {
        trimmed["local ".len()..].to_string()
    } else {
        code.to_string()
    }
}

fn lua_display(v: &mlua::Value) -> String {
    match v {
        mlua::Value::Nil        => "nil".into(),
        mlua::Value::Boolean(b) => b.to_string(),
        mlua::Value::Integer(i) => i.to_string(),
        mlua::Value::Number(f)  => f.to_string(),
        mlua::Value::String(s)  => format!("\"{}\"", String::from_utf8_lossy(&s.as_bytes())),
        mlua::Value::Table(t)   => {
            let pairs: Vec<String> = t.clone().pairs::<mlua::Value, mlua::Value>()
                .filter_map(|r| r.ok())
                .map(|(k, v)| format!("{}: {}", lua_display(&k), lua_display(&v)))
                .collect();
            format!("{{ {} }}", pairs.join(", "))
        }
        other => format!("{other:?}"),
    }
}
