use std::cell::RefCell;
use std::path::Path;
use std::rc::Rc;

use mlua::Lua;
use rustyline::DefaultEditor;
use rustyline::error::ReadlineError;

use crate::graph::graphstore::graphstore::GraphStore;
use crate::lua::graph_store::LuaGraphStore;
use crate::storage::page_store::PageStore;

pub enum OpenMode {
    /// Open if exists, create if not.
    Auto,
    /// Always create — return an error if the file already exists.
    ForceNew,
}

/// Run a Lua script (source string) against a database file non-interactively.
/// The script executes inside the same sandbox as the REPL. Output comes from
/// explicit `print()` calls only — there is no auto-printing of expressions.
pub fn exec_script(
    path: &Path,
    script: &str,
    mode: OpenMode,
    use_wal: bool,
    use_mmap: bool,
) -> Result<(), Box<dyn std::error::Error>> {
    let exists = path.exists();
    if matches!(mode, OpenMode::ForceNew) && exists {
        return Err(format!("'{}' already exists (omit --new to open it)", path.display()).into());
    }
    if use_mmap {
        let store = if exists { GraphStore::open_mmap(path)? } else { GraphStore::create_mmap(path)? };
        exec_inner(Rc::new(RefCell::new(store)), script)
    } else if use_wal {
        let store = if exists { GraphStore::open_wal(path)? } else { GraphStore::create_wal(path)? };
        exec_inner(Rc::new(RefCell::new(store)), script)
    } else {
        let store = if exists { GraphStore::open(path)? } else { GraphStore::create(path)? };
        exec_inner(Rc::new(RefCell::new(store)), script)
    }
}

// AI_GENERATED: Generated by AI (CLAUDE_CODE)
fn exec_inner<S: PageStore + 'static>(
    shared: Rc<RefCell<GraphStore<S>>>,
    script: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let lua = Lua::new();
    let sandbox = make_sandbox(&lua, &shared)?;
    lua.load(script).set_environment(sandbox).exec()?;
    shared.borrow_mut().close()?;
    Ok(())
}

pub fn run(path: &Path, mode: OpenMode, use_wal: bool, use_mmap: bool) -> Result<(), Box<dyn std::error::Error>> {
    let exists = path.exists();
    let created = matches!(mode, OpenMode::ForceNew) || !exists;
    if matches!(mode, OpenMode::ForceNew) && exists {
        return Err(format!("'{}' already exists (omit --new to open it)", path.display()).into());
    }
    if use_mmap {
        let store = if exists { GraphStore::open_mmap(path)? } else { GraphStore::create_mmap(path)? };
        run_inner(path, created, Rc::new(RefCell::new(store)))
    } else if use_wal {
        let store = if exists { GraphStore::open_wal(path)? } else { GraphStore::create_wal(path)? };
        run_inner(path, created, Rc::new(RefCell::new(store)))
    } else {
        let store = if exists { GraphStore::open(path)? } else { GraphStore::create(path)? };
        run_inner(path, created, Rc::new(RefCell::new(store)))
    }
}

// AI_GENERATED: Generated by AI (CLAUDE_CODE)
fn run_inner<S: PageStore + 'static>(
    path: &Path,
    created: bool,
    shared: Rc<RefCell<GraphStore<S>>>,
) -> Result<(), Box<dyn std::error::Error>> {
    let lua = Lua::new();

    // Build a sandboxed environment — only whitelisted globals are visible.
    // Scripts cannot reach os, io, require, load, or any other escape hatch.
    let env = make_sandbox(&lua, &shared)?;

    // Pre-load help() into globals (pure Lua, no env dependency), then copy
    // it into the sandbox so it is accessible from the REPL.
    lua.load(r#"
        function help()
            print([[
Nodes
  db:insert_node(label)                         → id
  db:get_node(id)                               → {id, label}
  db:update_node(id, label)
  db:delete_node(id)

Edges
  db:insert_edge(src, dst, label, weight)       → id
  db:get_edge(id)                               → {id, src, dst, label, weight}
  db:update_edge(id, label, weight)
  db:delete_edge(id)

Properties
  db:set_node_property(id, key, value)
  db:get_node_property(id, key)                 → value or nil
  db:delete_node_property(id, key)              → bool
  db:set_edge_property(id, key, value)
  db:get_edge_property(id, key)                 → value or nil
  db:delete_edge_property(id, key)              → bool

Cursor traversal
  db:outgoing_cursor(node_id)                   → cursor
  db:incoming_cursor(node_id)                   → cursor
  db:next_outgoing(cursor)                      → edge or nil
  db:next_incoming(cursor)                      → edge or nil

Scan
  db:all_nodes_cursor()                         → cursor
  db:all_edges_cursor()                         → cursor
  db:next_node(cursor)                          → node or nil
  db:next_edge(cursor)                          → edge or nil

Property iteration
  db:node_properties_cursor(node_id)            → cursor
  db:edge_properties_cursor(edge_id)            → cursor
  db:next_property(cursor)                      → {key, value} or nil

High-level traversal  (return false from callback to stop early)
  db:for_each_outgoing(node_id, fn(edge))
  db:for_each_incoming(node_id, fn(edge))
  db:for_each_with_label(label, fn(node))
  db:bfs(start, max_depth, fn(node, depth))
  db:dfs(start, max_depth, fn(node, depth))
  db:has_path(src, dst)                         → bool
  db:shortest_path(src, dst)                    → {id, ...} or nil
]])
        end
    "#).exec()?;
    let help_fn: mlua::Value = lua.globals().get("help")?;
    env.set("help", help_fn)?;

    print_banner(path, created);

    let mut rl = DefaultEditor::new()?;
    let mut pending = String::new();

    loop {
        let prompt = if pending.is_empty() { "nexora> " } else { "  ...  > " };
        match rl.readline(prompt) {
            Ok(line) => {
                pending.push_str(&line);
                pending.push('\n');

                let code = strip_local(&pending);

                // Try as expression first so bare values print automatically.
                let expr = format!("return {}", code.trim_end());
                if let Ok(vals) = lua.load(&expr).set_environment(env.clone()).eval::<mlua::MultiValue>() {
                    let _ = rl.add_history_entry(pending.trim());
                    pending.clear();
                    let parts: Vec<String> = vals.iter().map(lua_display).collect();
                    if !parts.is_empty() { println!("{}", parts.join("\t")); }
                    continue;
                }

                match lua.load(&code).set_environment(env.clone()).exec() {
                    Ok(_) => {
                        let _ = rl.add_history_entry(pending.trim());
                        pending.clear();
                    }
                    Err(mlua::Error::SyntaxError { incomplete_input: true, .. }) => {}
                    Err(e) => {
                        eprintln!("error: {e}");
                        pending.clear();
                    }
                }
            }
            Err(ReadlineError::Interrupted) => {
                pending.clear();
                println!("(interrupted — Ctrl-D to quit)");
            }
            Err(_) => break,
        }
    }

    shared.borrow_mut().close()?;
    println!("\nBye.");
    Ok(())
}

fn print_banner(path: &Path, created: bool) {
    let status = if created { "created" } else { "opened" };
    let db_str = path.display().to_string();
    println!();
    println!("  Nexora {}  —  embedded graph database", env!("CARGO_PKG_VERSION"));
    println!("  ─────────────────────────────────────────");
    println!("  db      {}  [{}]", db_str, status);
    println!("  engine  Lua 5.4");
    println!("  hint    type help() for API reference, Ctrl-D to quit");
    println!();
}

// Build a sandboxed Lua environment containing only whitelisted globals.
// Scripts run inside this env cannot reach os, io, require, load, or any
// other escape hatch — only the db handle and safe standard library subsets.
pub fn make_sandbox<S: PageStore + 'static>(
    lua: &Lua,
    shared: &Rc<RefCell<GraphStore<S>>>,
) -> mlua::Result<mlua::Table> {
    let sandbox = lua.create_table()?;
    let globals = lua.globals();

    for name in &["math", "string", "table"] {
        sandbox.set(*name, globals.get::<mlua::Value>(*name)?)?;
    }

    for name in &[
        "ipairs", "pairs", "next", "select", "type",
        "tostring", "tonumber", "pcall", "xpcall",
        "error", "assert", "print",
        "setmetatable", "getmetatable",
        "rawget", "rawset", "rawequal", "rawlen",
        "_VERSION",
    ] {
        sandbox.set(*name, globals.get::<mlua::Value>(*name)?)?;
    }

    sandbox.set("db", LuaGraphStore(Rc::clone(shared)))?;
    Ok(sandbox)
}

fn strip_local(code: &str) -> String {
    let trimmed = code.trim();
    let lines: Vec<&str> = trimmed.lines().collect();
    if lines.len() == 1 && trimmed.starts_with("local ") {
        trimmed["local ".len()..].to_string()
    } else {
        code.to_string()
    }
}

fn lua_display(v: &mlua::Value) -> String {
    match v {
        mlua::Value::Nil        => "nil".into(),
        mlua::Value::Boolean(b) => b.to_string(),
        mlua::Value::Integer(i) => i.to_string(),
        mlua::Value::Number(f)  => f.to_string(),
        mlua::Value::String(s)  => format!("\"{}\"", String::from_utf8_lossy(&s.as_bytes())),
        mlua::Value::Table(t)   => {
            let pairs: Vec<String> = t.clone().pairs::<mlua::Value, mlua::Value>()
                .filter_map(|r| r.ok())
                .map(|(k, v)| format!("{}: {}", lua_display(&k), lua_display(&v)))
                .collect();
            format!("{{ {} }}", pairs.join(", "))
        }
        other => format!("{other:?}"),
    }
}
