// AI_GENERATED: Generated by AI (CLAUDE_CODE)
#[cfg(all(test, feature = "lua"))]
mod tests {
    use std::cell::RefCell;
    use std::path::{Path, PathBuf};
    use std::rc::Rc;

    use mlua::Lua;

    use crate::graph::graphstore::graphstore::GraphStore;
    use crate::lua::graph_store::LuaGraphStore;

    const LARGE_STACK: usize = 16 * 1024 * 1024;

    fn tmp_path(name: &str) -> PathBuf {
        std::env::temp_dir().join(name)
    }

    fn cleanup(path: &PathBuf) {
        let _ = std::fs::remove_file(path);
    }

    fn run<F: FnOnce() + Send + 'static>(f: F) {
        std::thread::Builder::new()
            .stack_size(LARGE_STACK)
            .spawn(f)
            .unwrap()
            .join()
            .unwrap();
    }

    fn setup_lua(path: &Path) -> (Lua, Rc<RefCell<GraphStore<crate::storage::page_store_disk::RegularPageStore>>>) {
        let store = GraphStore::create(path).unwrap();
        let shared = Rc::new(RefCell::new(store));
        let lua = Lua::new();
        lua.globals().set("db", LuaGraphStore(Rc::clone(&shared))).unwrap();
        (lua, shared)
    }

    // Test 1 — insert_node and get_node round-trip
    #[test]
    fn test_lua_insert_and_get_node() {
        let path = tmp_path("test_lua_insert_get_node.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local id = db:insert_node("Person")
                local node = db:get_node(id)
                assert(node.id == id, "id mismatch")
                assert(node.label == "Person", "label mismatch")
            "#).exec().unwrap();
            cleanup(&path);
        });
    }

    // Test 2 — multiple nodes get different IDs
    #[test]
    fn test_lua_multiple_nodes_distinct_ids() {
        let path = tmp_path("test_lua_multi_node_ids.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local a = db:insert_node("Person")
                local b = db:insert_node("City")
                assert(a ~= b, "ids should differ")
                assert(db:get_node(a).label == "Person")
                assert(db:get_node(b).label == "City")
            "#).exec().unwrap();
            cleanup(&path);
        });
    }

    // Test 3 — insert_edge and get_edge round-trip
    #[test]
    fn test_lua_insert_and_get_edge() {
        let path = tmp_path("test_lua_insert_get_edge.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local a   = db:insert_node("A")
                local b   = db:insert_node("B")
                local eid = db:insert_edge(a, b, "KNOWS", 1.5)
                local e   = db:get_edge(eid)
                assert(e.id    == eid,    "edge id mismatch")
                assert(e.src   == a,      "src mismatch")
                assert(e.dst   == b,      "dst mismatch")
                assert(e.label == "KNOWS","label mismatch")
                assert(math.abs(e.weight - 1.5) < 0.001, "weight mismatch")
            "#).exec().unwrap();
            cleanup(&path);
        });
    }

    // Test 4 — delete_node removes the node
    #[test]
    fn test_lua_delete_node() {
        let path = tmp_path("test_lua_delete_node.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local id = db:insert_node("Person")
                db:delete_node(id)
            "#).exec().unwrap();
            // get_node on deleted id should error
            assert!(lua.load("db:get_node(0)").exec().is_err());
            cleanup(&path);
        });
    }

    // Test 5 — delete_edge removes the edge
    #[test]
    fn test_lua_delete_edge() {
        let path = tmp_path("test_lua_delete_edge.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local a   = db:insert_node("A")
                local b   = db:insert_node("B")
                local eid = db:insert_edge(a, b, "REL", 1.0)
                db:delete_edge(eid)
            "#).exec().unwrap();
            assert!(lua.load("db:get_edge(0)").exec().is_err());
            cleanup(&path);
        });
    }

    // Test 6 — update_node changes the label
    #[test]
    fn test_lua_update_node() {
        let path = tmp_path("test_lua_update_node.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local id = db:insert_node("Person")
                db:update_node(id, "Company")
                assert(db:get_node(id).label == "Company")
            "#).exec().unwrap();
            cleanup(&path);
        });
    }

    // Test 7 — update_edge changes label and weight
    #[test]
    fn test_lua_update_edge() {
        let path = tmp_path("test_lua_update_edge.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local a   = db:insert_node("A")
                local b   = db:insert_node("B")
                local eid = db:insert_edge(a, b, "KNOWS", 1.0)
                db:update_edge(eid, "LIKES", 9.0)
                local e = db:get_edge(eid)
                assert(e.label == "LIKES")
                assert(math.abs(e.weight - 9.0) < 0.001)
                assert(e.src == a and e.dst == b, "src/dst must not change")
            "#).exec().unwrap();
            cleanup(&path);
        });
    }

    // Test 8 — set and get a node property
    #[test]
    fn test_lua_node_property_set_get() {
        let path = tmp_path("test_lua_node_prop_set_get.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local id = db:insert_node("Person")
                db:set_node_property(id, "name", "Alice")
                local v = db:get_node_property(id, "name")
                assert(v == "Alice", "expected Alice got " .. tostring(v))
            "#).exec().unwrap();
            cleanup(&path);
        });
    }

    // Test 9 — get nonexistent node property returns nil
    #[test]
    fn test_lua_node_property_missing_is_nil() {
        let path = tmp_path("test_lua_node_prop_nil.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local id = db:insert_node("Person")
                local v = db:get_node_property(id, "missing")
                assert(v == nil, "expected nil")
            "#).exec().unwrap();
            cleanup(&path);
        });
    }

    // Test 10 — updating a node property overwrites the value
    #[test]
    fn test_lua_node_property_update() {
        let path = tmp_path("test_lua_node_prop_update.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local id = db:insert_node("Person")
                db:set_node_property(id, "name", "Alice")
                db:set_node_property(id, "name", "Bob")
                assert(db:get_node_property(id, "name") == "Bob")
            "#).exec().unwrap();
            cleanup(&path);
        });
    }

    // Test 11 — delete a node property, subsequent get returns nil
    #[test]
    fn test_lua_node_property_delete() {
        let path = tmp_path("test_lua_node_prop_delete.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local id = db:insert_node("Person")
                db:set_node_property(id, "name", "Alice")
                local deleted = db:delete_node_property(id, "name")
                assert(deleted == true)
                assert(db:get_node_property(id, "name") == nil)
            "#).exec().unwrap();
            cleanup(&path);
        });
    }

    // Test 12 — set and get an edge property
    #[test]
    fn test_lua_edge_property_set_get() {
        let path = tmp_path("test_lua_edge_prop_set_get.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local a   = db:insert_node("A")
                local b   = db:insert_node("B")
                local eid = db:insert_edge(a, b, "REL", 1.0)
                db:set_edge_property(eid, "since", "2024")
                assert(db:get_edge_property(eid, "since") == "2024")
            "#).exec().unwrap();
            cleanup(&path);
        });
    }

    // Test 13 — delete an edge property, subsequent get returns nil
    #[test]
    fn test_lua_edge_property_delete() {
        let path = tmp_path("test_lua_edge_prop_delete.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local a   = db:insert_node("A")
                local b   = db:insert_node("B")
                local eid = db:insert_edge(a, b, "REL", 1.0)
                db:set_edge_property(eid, "since", "2024")
                local deleted = db:delete_edge_property(eid, "since")
                assert(deleted == true)
                assert(db:get_edge_property(eid, "since") == nil)
            "#).exec().unwrap();
            cleanup(&path);
        });
    }

    // Test 14 — outgoing cursor visits all edges from a node
    #[test]
    fn test_lua_outgoing_cursor() {
        let path = tmp_path("test_lua_outgoing_cursor.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local a = db:insert_node("A")
                local b = db:insert_node("B")
                local c = db:insert_node("C")
                local e1 = db:insert_edge(a, b, "REL", 1.0)
                local e2 = db:insert_edge(a, c, "REL", 2.0)

                local cursor = db:outgoing_cursor(a)
                local count = 0
                while true do
                    local edge = db:next_outgoing(cursor)
                    if edge == nil then break end
                    count = count + 1
                end
                assert(count == 2, "expected 2 outgoing edges, got " .. count)
            "#).exec().unwrap();
            cleanup(&path);
        });
    }

    // Test 15 — incoming cursor visits all edges to a node
    #[test]
    fn test_lua_incoming_cursor() {
        let path = tmp_path("test_lua_incoming_cursor.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local a = db:insert_node("A")
                local b = db:insert_node("B")
                local c = db:insert_node("C")
                db:insert_edge(a, c, "REL", 1.0)
                db:insert_edge(b, c, "REL", 2.0)

                local cursor = db:incoming_cursor(c)
                local count = 0
                while true do
                    local edge = db:next_incoming(cursor)
                    if edge == nil then break end
                    count = count + 1
                end
                assert(count == 2, "expected 2 incoming edges, got " .. count)
            "#).exec().unwrap();
            cleanup(&path);
        });
    }

    // Test 16 — outgoing cursor on node with no edges is immediately empty
    #[test]
    fn test_lua_outgoing_cursor_empty() {
        let path = tmp_path("test_lua_outgoing_empty.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local a = db:insert_node("A")
                local cursor = db:outgoing_cursor(a)
                local edge = db:next_outgoing(cursor)
                assert(edge == nil, "expected nil for empty outgoing")
            "#).exec().unwrap();
            cleanup(&path);
        });
    }

    // Test 17 — scan all nodes visits every inserted node
    #[test]
    fn test_lua_scan_all_nodes() {
        let path = tmp_path("test_lua_scan_nodes.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                db:insert_node("Person")
                db:insert_node("City")
                db:insert_node("Company")

                local cursor = db:all_nodes_cursor()
                local count = 0
                while true do
                    local node = db:next_node(cursor)
                    if node == nil then break end
                    count = count + 1
                end
                assert(count == 3, "expected 3 nodes, got " .. count)
            "#).exec().unwrap();
            cleanup(&path);
        });
    }

    // Test 18 — scan all edges visits every inserted edge
    #[test]
    fn test_lua_scan_all_edges() {
        let path = tmp_path("test_lua_scan_edges.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local a = db:insert_node("A")
                local b = db:insert_node("B")
                local c = db:insert_node("C")
                db:insert_edge(a, b, "R", 1.0)
                db:insert_edge(b, c, "R", 2.0)
                db:insert_edge(a, c, "R", 3.0)

                local cursor = db:all_edges_cursor()
                local count = 0
                while true do
                    local edge = db:next_edge(cursor)
                    if edge == nil then break end
                    count = count + 1
                end
                assert(count == 3, "expected 3 edges, got " .. count)
            "#).exec().unwrap();
            cleanup(&path);
        });
    }

    // Test 19 — node property iteration visits all properties
    #[test]
    fn test_lua_node_property_iteration() {
        let path = tmp_path("test_lua_prop_iter.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local id = db:insert_node("Person")
                db:set_node_property(id, "name", "Alice")
                db:set_node_property(id, "age",  "30")
                db:set_node_property(id, "city", "London")

                local cursor = db:node_properties_cursor(id)
                local count = 0
                while true do
                    local prop = db:next_property(cursor)
                    if prop == nil then break end
                    assert(type(prop.key)   == "string")
                    assert(type(prop.value) == "string")
                    count = count + 1
                end
                assert(count == 3, "expected 3 properties, got " .. count)
            "#).exec().unwrap();
            cleanup(&path);
        });
    }

    // Test 20 — edge property iteration visits all properties
    #[test]
    fn test_lua_edge_property_iteration() {
        let path = tmp_path("test_lua_edge_prop_iter.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local a   = db:insert_node("A")
                local b   = db:insert_node("B")
                local eid = db:insert_edge(a, b, "REL", 1.0)
                db:set_edge_property(eid, "since",  "2020")
                db:set_edge_property(eid, "weight", "heavy")

                local cursor = db:edge_properties_cursor(eid)
                local count = 0
                while true do
                    local prop = db:next_property(cursor)
                    if prop == nil then break end
                    count = count + 1
                end
                assert(count == 2, "expected 2 edge properties, got " .. count)
            "#).exec().unwrap();
            cleanup(&path);
        });
    }

    // Test 21 — delete_node cascades to incident edges
    #[test]
    fn test_lua_delete_node_cascades() {
        let path = tmp_path("test_lua_delete_cascade.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local a = db:insert_node("A")
                local b = db:insert_node("B")
                local c = db:insert_node("C")
                local e1 = db:insert_edge(a, b, "R", 1.0)
                local e2 = db:insert_edge(c, a, "R", 2.0)
                db:delete_node(a)
                -- b and c must still exist
                assert(db:get_node(b) ~= nil)
                assert(db:get_node(c) ~= nil)
            "#).exec().unwrap();
            // incident edges should now be gone
            assert!(lua.load("db:get_edge(0)").exec().is_err());
            cleanup(&path);
        });
    }

    // Test 22 — get_node on unknown id raises a Lua error
    #[test]
    fn test_lua_get_unknown_node_errors() {
        let path = tmp_path("test_lua_unknown_node.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            assert!(lua.load("db:get_node(999999)").exec().is_err());
            cleanup(&path);
        });
    }

    // Test 23 — get_edge on unknown id raises a Lua error
    #[test]
    fn test_lua_get_unknown_edge_errors() {
        let path = tmp_path("test_lua_unknown_edge.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            assert!(lua.load("db:get_edge(999999)").exec().is_err());
            cleanup(&path);
        });
    }

    // Test 24 — multiple properties on same node, each retrievable by key
    #[test]
    fn test_lua_multiple_node_properties() {
        let path = tmp_path("test_lua_multi_node_props.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local id = db:insert_node("Person")
                db:set_node_property(id, "name", "Alice")
                db:set_node_property(id, "age",  "30")
                assert(db:get_node_property(id, "name") == "Alice")
                assert(db:get_node_property(id, "age")  == "30")
            "#).exec().unwrap();
            cleanup(&path);
        });
    }

    // Test 25 — edge fields (src, dst, label, weight) are accessible from Lua
    #[test]
    fn test_lua_edge_fields_accessible() {
        let path = tmp_path("test_lua_edge_fields.nxr");
        cleanup(&path);
        run(move || {
            let (lua, _shared) = setup_lua(&path);
            lua.load(r#"
                local a   = db:insert_node("A")
                local b   = db:insert_node("B")
                local eid = db:insert_edge(a, b, "LIKES", 3.14)
                local e   = db:get_edge(eid)
                assert(e.src   == a)
                assert(e.dst   == b)
                assert(e.label == "LIKES")
                assert(math.abs(e.weight - 3.14) < 0.001)
            "#).exec().unwrap();
            cleanup(&path);
        });
    }
}
