// AI_GENERATED: Generated by AI (CLAUDE_CODE)
#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use crate::api::traversal::{Traversal, TraverseApi, Visit};
    use crate::graph::graphstore::graphstore::GraphStore;

    const LARGE_STACK: usize = 16 * 1024 * 1024;

    fn tmp_path(name: &str) -> PathBuf {
        std::env::temp_dir().join(name)
    }

    fn cleanup(path: &PathBuf) {
        let _ = std::fs::remove_file(path);
    }

    fn run<F: FnOnce() + Send + 'static>(f: F) {
        std::thread::Builder::new()
            .stack_size(LARGE_STACK)
            .spawn(f)
            .unwrap()
            .join()
            .unwrap();
    }

    // ── for_each_outgoing ─────────────────────────────────────────────────────

    #[test]
    fn test_for_each_outgoing_visits_all_edges() {
        let path = tmp_path("test_trav_outgoing_all.nxr");
        cleanup(&path);
        run(move || {
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();
            let b = gs.insert_node("B").unwrap();
            let c = gs.insert_node("C").unwrap();
            gs.insert_edge(a, b, "X", 1.0).unwrap();
            gs.insert_edge(a, c, "Y", 2.0).unwrap();

            let mut visited = vec![];
            Traversal::new(&mut gs)
                .for_each_outgoing(a, |e| {
                    visited.push(e.dst);
                    Visit::Continue
                })
                .unwrap();

            assert_eq!(visited.len(), 2);
            assert!(visited.contains(&b));
            assert!(visited.contains(&c));
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    #[test]
    fn test_for_each_outgoing_early_stop() {
        let path = tmp_path("test_trav_outgoing_stop.nxr");
        cleanup(&path);
        run(move || {
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();
            let b = gs.insert_node("B").unwrap();
            let c = gs.insert_node("C").unwrap();
            gs.insert_edge(a, b, "X", 1.0).unwrap();
            gs.insert_edge(a, c, "Y", 2.0).unwrap();

            let mut count = 0;
            Traversal::new(&mut gs)
                .for_each_outgoing(a, |_e| {
                    count += 1;
                    Visit::Stop
                })
                .unwrap();

            assert_eq!(count, 1);
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    #[test]
    fn test_for_each_outgoing_no_edges() {
        let path = tmp_path("test_trav_outgoing_empty.nxr");
        cleanup(&path);
        run(move || {
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();

            let mut count = 0;
            Traversal::new(&mut gs)
                .for_each_outgoing(a, |_e| {
                    count += 1;
                    Visit::Continue
                })
                .unwrap();

            assert_eq!(count, 0);
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    // ── for_each_incoming ─────────────────────────────────────────────────────

    #[test]
    fn test_for_each_incoming_visits_all_edges() {
        let path = tmp_path("test_trav_incoming_all.nxr");
        cleanup(&path);
        run(move || {
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();
            let b = gs.insert_node("B").unwrap();
            let c = gs.insert_node("C").unwrap();
            gs.insert_edge(a, c, "X", 1.0).unwrap();
            gs.insert_edge(b, c, "Y", 2.0).unwrap();

            let mut srcs = vec![];
            Traversal::new(&mut gs)
                .for_each_incoming(c, |e| {
                    srcs.push(e.src);
                    Visit::Continue
                })
                .unwrap();

            assert_eq!(srcs.len(), 2);
            assert!(srcs.contains(&a));
            assert!(srcs.contains(&b));
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    // ── bfs ───────────────────────────────────────────────────────────────────

    #[test]
    fn test_bfs_visits_all_reachable_nodes() {
        let path = tmp_path("test_trav_bfs_all.nxr");
        cleanup(&path);
        run(move || {
            // a -> b -> c -> d
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();
            let b = gs.insert_node("B").unwrap();
            let c = gs.insert_node("C").unwrap();
            let d = gs.insert_node("D").unwrap();
            gs.insert_edge(a, b, "E", 1.0).unwrap();
            gs.insert_edge(b, c, "E", 1.0).unwrap();
            gs.insert_edge(c, d, "E", 1.0).unwrap();

            let mut ids = vec![];
            Traversal::new(&mut gs)
                .bfs(a, 10, |node, _depth| {
                    ids.push(node.id);
                    Visit::Continue
                })
                .unwrap();

            assert_eq!(ids, vec![a, b, c, d]);
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    #[test]
    fn test_bfs_respects_max_depth() {
        let path = tmp_path("test_trav_bfs_depth.nxr");
        cleanup(&path);
        run(move || {
            // a -> b -> c -> d
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();
            let b = gs.insert_node("B").unwrap();
            let c = gs.insert_node("C").unwrap();
            let d = gs.insert_node("D").unwrap();
            gs.insert_edge(a, b, "E", 1.0).unwrap();
            gs.insert_edge(b, c, "E", 1.0).unwrap();
            gs.insert_edge(c, d, "E", 1.0).unwrap();

            let mut ids = vec![];
            Traversal::new(&mut gs)
                .bfs(a, 2, |node, _depth| {
                    ids.push(node.id);
                    Visit::Continue
                })
                .unwrap();

            // depth 0 = a, 1 = b, 2 = c; d is at depth 3 and must be excluded
            assert_eq!(ids, vec![a, b, c]);
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    #[test]
    fn test_bfs_visits_node_once_despite_multiple_paths() {
        let path = tmp_path("test_trav_bfs_dedup.nxr");
        cleanup(&path);
        run(move || {
            // a -> b, a -> c, b -> d, c -> d
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();
            let b = gs.insert_node("B").unwrap();
            let c = gs.insert_node("C").unwrap();
            let d = gs.insert_node("D").unwrap();
            gs.insert_edge(a, b, "E", 1.0).unwrap();
            gs.insert_edge(a, c, "E", 1.0).unwrap();
            gs.insert_edge(b, d, "E", 1.0).unwrap();
            gs.insert_edge(c, d, "E", 1.0).unwrap();

            let mut ids = vec![];
            Traversal::new(&mut gs)
                .bfs(a, 10, |node, _depth| {
                    ids.push(node.id);
                    Visit::Continue
                })
                .unwrap();

            let d_count = ids.iter().filter(|&&x| x == d).count();
            assert_eq!(d_count, 1, "d should be visited exactly once");
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    #[test]
    fn test_bfs_handles_cycle() {
        let path = tmp_path("test_trav_bfs_cycle.nxr");
        cleanup(&path);
        run(move || {
            // a -> b -> a  (cycle)
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();
            let b = gs.insert_node("B").unwrap();
            gs.insert_edge(a, b, "E", 1.0).unwrap();
            gs.insert_edge(b, a, "E", 1.0).unwrap();

            let mut ids = vec![];
            Traversal::new(&mut gs)
                .bfs(a, 10, |node, _depth| {
                    ids.push(node.id);
                    Visit::Continue
                })
                .unwrap();

            assert_eq!(ids.len(), 2);
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    #[test]
    fn test_bfs_early_stop() {
        let path = tmp_path("test_trav_bfs_stop.nxr");
        cleanup(&path);
        run(move || {
            // a -> b -> c
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();
            let b = gs.insert_node("B").unwrap();
            let c = gs.insert_node("C").unwrap();
            gs.insert_edge(a, b, "E", 1.0).unwrap();
            gs.insert_edge(b, c, "E", 1.0).unwrap();

            let mut ids = vec![];
            Traversal::new(&mut gs)
                .bfs(a, 10, |node, _depth| {
                    ids.push(node.id);
                    if node.id == b {
                        Visit::Stop
                    } else {
                        Visit::Continue
                    }
                })
                .unwrap();

            assert_eq!(ids, vec![a, b]);
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    #[test]
    fn test_bfs_reports_correct_depth() {
        let path = tmp_path("test_trav_bfs_depth_values.nxr");
        cleanup(&path);
        run(move || {
            // a -> b -> c
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();
            let b = gs.insert_node("B").unwrap();
            let c = gs.insert_node("C").unwrap();
            gs.insert_edge(a, b, "E", 1.0).unwrap();
            gs.insert_edge(b, c, "E", 1.0).unwrap();

            let mut depths = vec![];
            Traversal::new(&mut gs)
                .bfs(a, 10, |_node, depth| {
                    depths.push(depth);
                    Visit::Continue
                })
                .unwrap();

            assert_eq!(depths, vec![0, 1, 2]);
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    // ── dfs ───────────────────────────────────────────────────────────────────

    #[test]
    fn test_dfs_visits_all_reachable_nodes() {
        let path = tmp_path("test_trav_dfs_all.nxr");
        cleanup(&path);
        run(move || {
            // a -> b -> c
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();
            let b = gs.insert_node("B").unwrap();
            let c = gs.insert_node("C").unwrap();
            gs.insert_edge(a, b, "E", 1.0).unwrap();
            gs.insert_edge(b, c, "E", 1.0).unwrap();

            let mut ids = vec![];
            Traversal::new(&mut gs)
                .dfs(a, 10, |node, _depth| {
                    ids.push(node.id);
                    Visit::Continue
                })
                .unwrap();

            assert_eq!(ids, vec![a, b, c]);
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    #[test]
    fn test_dfs_respects_max_depth() {
        let path = tmp_path("test_trav_dfs_depth.nxr");
        cleanup(&path);
        run(move || {
            // a -> b -> c -> d
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();
            let b = gs.insert_node("B").unwrap();
            let c = gs.insert_node("C").unwrap();
            let d = gs.insert_node("D").unwrap();
            gs.insert_edge(a, b, "E", 1.0).unwrap();
            gs.insert_edge(b, c, "E", 1.0).unwrap();
            gs.insert_edge(c, d, "E", 1.0).unwrap();

            let mut ids = vec![];
            Traversal::new(&mut gs)
                .dfs(a, 2, |node, _depth| {
                    ids.push(node.id);
                    Visit::Continue
                })
                .unwrap();

            assert!(!ids.contains(&d), "d at depth 3 should not be visited");
            assert!(ids.contains(&a) && ids.contains(&b) && ids.contains(&c));
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    #[test]
    fn test_dfs_handles_cycle() {
        let path = tmp_path("test_trav_dfs_cycle.nxr");
        cleanup(&path);
        run(move || {
            // a -> b -> a  (cycle)
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();
            let b = gs.insert_node("B").unwrap();
            gs.insert_edge(a, b, "E", 1.0).unwrap();
            gs.insert_edge(b, a, "E", 1.0).unwrap();

            let mut ids = vec![];
            Traversal::new(&mut gs)
                .dfs(a, 10, |node, _depth| {
                    ids.push(node.id);
                    Visit::Continue
                })
                .unwrap();

            assert_eq!(ids.len(), 2);
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    // ── has_path ──────────────────────────────────────────────────────────────

    #[test]
    fn test_has_path_direct_edge() {
        let path = tmp_path("test_trav_haspath_direct.nxr");
        cleanup(&path);
        run(move || {
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();
            let b = gs.insert_node("B").unwrap();
            gs.insert_edge(a, b, "E", 1.0).unwrap();

            assert!(Traversal::new(&mut gs).has_path(a, b).unwrap());
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    #[test]
    fn test_has_path_multi_hop() {
        let path = tmp_path("test_trav_haspath_multihop.nxr");
        cleanup(&path);
        run(move || {
            // a -> b -> c
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();
            let b = gs.insert_node("B").unwrap();
            let c = gs.insert_node("C").unwrap();
            gs.insert_edge(a, b, "E", 1.0).unwrap();
            gs.insert_edge(b, c, "E", 1.0).unwrap();

            assert!(Traversal::new(&mut gs).has_path(a, c).unwrap());
            assert!(!Traversal::new(&mut gs).has_path(c, a).unwrap());
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    #[test]
    fn test_has_path_self() {
        let path = tmp_path("test_trav_haspath_self.nxr");
        cleanup(&path);
        run(move || {
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();

            assert!(Traversal::new(&mut gs).has_path(a, a).unwrap());
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    #[test]
    fn test_has_path_unreachable() {
        let path = tmp_path("test_trav_haspath_unreachable.nxr");
        cleanup(&path);
        run(move || {
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();
            let b = gs.insert_node("B").unwrap();
            // No edge between a and b

            assert!(!Traversal::new(&mut gs).has_path(a, b).unwrap());
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    // ── shortest_path ─────────────────────────────────────────────────────────

    #[test]
    fn test_shortest_path_self() {
        let path = tmp_path("test_trav_sp_self.nxr");
        cleanup(&path);
        run(move || {
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();

            let p = Traversal::new(&mut gs).shortest_path(a, a).unwrap();
            assert_eq!(p, Some(vec![a]));
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    #[test]
    fn test_shortest_path_direct_edge() {
        let path = tmp_path("test_trav_sp_direct.nxr");
        cleanup(&path);
        run(move || {
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();
            let b = gs.insert_node("B").unwrap();
            gs.insert_edge(a, b, "E", 1.0).unwrap();

            let p = Traversal::new(&mut gs).shortest_path(a, b).unwrap();
            assert_eq!(p, Some(vec![a, b]));
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    #[test]
    fn test_shortest_path_multi_hop() {
        let path = tmp_path("test_trav_sp_multihop.nxr");
        cleanup(&path);
        run(move || {
            // a -> b -> c -> d
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();
            let b = gs.insert_node("B").unwrap();
            let c = gs.insert_node("C").unwrap();
            let d = gs.insert_node("D").unwrap();
            gs.insert_edge(a, b, "E", 1.0).unwrap();
            gs.insert_edge(b, c, "E", 1.0).unwrap();
            gs.insert_edge(c, d, "E", 1.0).unwrap();

            let p = Traversal::new(&mut gs).shortest_path(a, d).unwrap();
            assert_eq!(p, Some(vec![a, b, c, d]));
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    #[test]
    fn test_shortest_path_picks_fewer_hops() {
        let path = tmp_path("test_trav_sp_fewer_hops.nxr");
        cleanup(&path);
        run(move || {
            // a -> c (direct), a -> b -> c (longer)
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();
            let b = gs.insert_node("B").unwrap();
            let c = gs.insert_node("C").unwrap();
            gs.insert_edge(a, b, "E", 1.0).unwrap();
            gs.insert_edge(b, c, "E", 1.0).unwrap();
            gs.insert_edge(a, c, "E", 1.0).unwrap();

            let p = Traversal::new(&mut gs).shortest_path(a, c).unwrap();
            assert_eq!(p, Some(vec![a, c]));
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    #[test]
    fn test_shortest_path_no_path() {
        let path = tmp_path("test_trav_sp_none.nxr");
        cleanup(&path);
        run(move || {
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();
            let b = gs.insert_node("B").unwrap();

            let p = Traversal::new(&mut gs).shortest_path(a, b).unwrap();
            assert_eq!(p, None);
            gs.close().unwrap();
            cleanup(&path);
        });
    }

    #[test]
    fn test_shortest_path_wrong_direction() {
        let path = tmp_path("test_trav_sp_direction.nxr");
        cleanup(&path);
        run(move || {
            // only a -> b; no path b -> a
            let mut gs = GraphStore::create(&path).unwrap();
            let a = gs.insert_node("A").unwrap();
            let b = gs.insert_node("B").unwrap();
            gs.insert_edge(a, b, "E", 1.0).unwrap();

            let p = Traversal::new(&mut gs).shortest_path(b, a).unwrap();
            assert_eq!(p, None);
            gs.close().unwrap();
            cleanup(&path);
        });
    }
}
