// AI_GENERATED: Generated by AI (CLAUDE_CODE)
#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use crate::graph::label::constants::MAX_PAGE_LABEL_COUNT;
    use crate::graph::label::error::NexoraGraphLabelError;
    use crate::graph::label::graph_label_store::LabelStore;
    use crate::storage::page_store_disk::RegularPageStore;
    use crate::storage::storage_manager::StorageManager;

    fn tmp_path(name: &str) -> PathBuf {
        std::env::temp_dir().join(name)
    }

    fn cleanup(path: &PathBuf) {
        let _ = std::fs::remove_file(path);
    }

    fn setup(path: &PathBuf) -> StorageManager<RegularPageStore> {
        let store = RegularPageStore::create(path).unwrap();
        StorageManager::from_page_store(store).unwrap()
    }

    // Test 1 — basic insert and get round-trip
    #[test]
    fn test_insert_and_get_label() {
        let path = tmp_path("test_label_insert_get.nxra");
        cleanup(&path);
        let mut manager = setup(&path);
        let mut store = LabelStore::new(&mut manager);

        let label_id = store.insert_label(b"Person").unwrap();

        let mut out = [0u8; 64];
        let len = store.get_label(label_id, &mut out).unwrap();

        assert_eq!(&out[..len as usize], b"Person");

        cleanup(&path);
    }

    // Test 2 — label IDs are sequential starting from 0
    #[test]
    fn test_label_ids_are_sequential() {
        let path = tmp_path("test_label_sequential.nxra");
        cleanup(&path);
        let mut manager = setup(&path);
        let mut store = LabelStore::new(&mut manager);

        let id0 = store.insert_label(b"Person").unwrap();
        let id1 = store.insert_label(b"KNOWS").unwrap();
        let id2 = store.insert_label(b"Company").unwrap();

        assert_eq!(id0, 0);
        assert_eq!(id1, 1);
        assert_eq!(id2, 2);

        cleanup(&path);
    }

    // Test 3 — multiple labels all readable
    #[test]
    fn test_multiple_labels() {
        let path = tmp_path("test_label_multiple.nxra");
        cleanup(&path);
        let mut manager = setup(&path);
        let mut store = LabelStore::new(&mut manager);

        let labels: &[&[u8]] = &[b"Person", b"KNOWS", b"age", b"name", b"Company"];
        let ids: Vec<u32> = labels.iter()
            .map(|l| store.insert_label(l).unwrap())
            .collect();

        for (id, expected) in ids.iter().zip(labels.iter()) {
            let mut out = [0u8; 64];
            let len = store.get_label(*id, &mut out).unwrap();
            assert_eq!(&out[..len as usize], *expected);
        }

        cleanup(&path);
    }

    // Test 4 — get nonexistent label returns LabelNotFound
    #[test]
    fn test_get_nonexistent_label() {
        let path = tmp_path("test_label_not_found.nxra");
        cleanup(&path);
        let mut manager = setup(&path);
        let mut store = LabelStore::new(&mut manager);

        assert!(matches!(store.get_label(999, &mut [0u8; 64]), Err(NexoraGraphLabelError::LabelNotFound)));

        cleanup(&path);
    }

    // Test 5 — labels survive close and reopen
    #[test]
    fn test_label_persistence() {
        let path = tmp_path("test_label_persistence.nxra");
        cleanup(&path);

        let label_id = {
            let mut manager = setup(&path);
            let id = {
                let mut store = LabelStore::new(&mut manager);
                store.insert_label(b"PersistedLabel").unwrap()
            };
            manager.close().unwrap();
            id
        };

        {
            let store = RegularPageStore::open(&path).unwrap();
            let mut manager = StorageManager::from_page_store(store).unwrap();
            let mut store = LabelStore::new(&mut manager);

            let mut out = [0u8; 64];
            let len = store.get_label(label_id, &mut out).unwrap();
            assert_eq!(&out[..len as usize], b"PersistedLabel");
        }

        cleanup(&path);
    }

    // Test 6 — inserting the same string twice returns the same label_id
    #[test]
    fn test_dedup_same_string_same_id() {
        let path = tmp_path("test_label_dedup_same.nxra");
        cleanup(&path);
        let mut manager = setup(&path);
        let mut store = LabelStore::new(&mut manager);

        let id0 = store.insert_label(b"Person").unwrap();
        let id1 = store.insert_label(b"Person").unwrap();
        assert_eq!(id0, id1);

        cleanup(&path);
    }

    // Test 7 — inserting the same string many times does not increment the count
    #[test]
    fn test_dedup_count_does_not_grow() {
        let path = tmp_path("test_label_dedup_count.nxra");
        cleanup(&path);
        let mut manager = setup(&path);
        let mut store = LabelStore::new(&mut manager);

        let id = store.insert_label(b"Person").unwrap();
        for _ in 0..9 {
            assert_eq!(store.insert_label(b"Person").unwrap(), id);
        }
        assert_eq!(manager.footer.label_pages_count.get(), 1);

        cleanup(&path);
    }

    // Test 8 — different strings get different label_ids
    #[test]
    fn test_dedup_different_strings_different_ids() {
        let path = tmp_path("test_label_dedup_diff.nxra");
        cleanup(&path);
        let mut manager = setup(&path);
        let mut store = LabelStore::new(&mut manager);

        let id0 = store.insert_label(b"Person").unwrap();
        let id1 = store.insert_label(b"Movie").unwrap();
        assert_ne!(id0, id1);

        cleanup(&path);
    }

    // Test 9 — dedup is case-sensitive
    #[test]
    fn test_dedup_case_sensitive() {
        let path = tmp_path("test_label_dedup_case.nxra");
        cleanup(&path);
        let mut manager = setup(&path);
        let mut store = LabelStore::new(&mut manager);

        let id_lower = store.insert_label(b"person").unwrap();
        let id_upper = store.insert_label(b"Person").unwrap();
        assert_ne!(id_lower, id_upper);

        cleanup(&path);
    }

    // Test 10 — dedup works when the duplicate is on a second label page
    #[test]
    fn test_dedup_across_page_boundary() {
        let path = tmp_path("test_label_dedup_overflow.nxra");
        cleanup(&path);
        let mut manager = setup(&path);
        let mut store = LabelStore::new(&mut manager);

        // Fill beyond one page with unique labels, then re-insert one from the first page.
        let count = MAX_PAGE_LABEL_COUNT as usize + 3;
        for i in 0..count {
            store.insert_label(format!("Label{}", i).as_bytes()).unwrap();
        }
        let id_again = store.insert_label(b"Label0").unwrap();
        assert_eq!(id_again, 0);

        cleanup(&path);
    }

    // Test 11 — dedup survives close and reopen
    #[test]
    fn test_dedup_persistence() {
        let path = tmp_path("test_label_dedup_persist.nxra");
        cleanup(&path);

        let id_first = {
            let mut manager = setup(&path);
            let id = LabelStore::new(&mut manager).insert_label(b"Person").unwrap();
            manager.close().unwrap();
            id
        };

        {
            let store = RegularPageStore::open(&path).unwrap();
            let mut manager = StorageManager::from_page_store(store).unwrap();
            let id_again = LabelStore::new(&mut manager).insert_label(b"Person").unwrap();
            assert_eq!(id_first, id_again);
        }

        cleanup(&path);
    }

    // Test 12 — insert enough labels to overflow onto a second page
    #[test]
    fn test_label_page_overflow() {
        let path = tmp_path("test_label_page_overflow.nxra");
        cleanup(&path);
        let mut manager = setup(&path);
        let mut store = LabelStore::new(&mut manager);

        let count = MAX_PAGE_LABEL_COUNT as usize + 5;
        let ids: Vec<u32> = (0..count)
            .map(|i| store.insert_label(format!("Label{}", i).as_bytes()).unwrap())
            .collect();

        for (i, id) in ids.iter().enumerate() {
            let expected = format!("Label{}", i);
            let mut out = [0u8; 32];
            let len = store.get_label(*id, &mut out).unwrap();
            assert_eq!(&out[..len as usize], expected.as_bytes());
        }

        cleanup(&path);
    }
}
