// AI_GENERATED: Generated by AI (CLAUDE_CODE)
#[cfg(test)]
mod tests {
    use super::*;
    use crate::storage::storage_manager::StorageManager;
    use crate::storage::error::NexoraStorageError;
    use crate::storage::models::PageId;
    use crate::storage::constants::PAGE_SIZE;
    use std::path::PathBuf;

    fn tmp_path(name: &str) -> PathBuf {
        std::env::temp_dir().join(name)
    }

    fn cleanup(path: &PathBuf) {
        let _ = std::fs::remove_file(path);
    }

    // Test 1 — create and reopen: header survives close/reopen cycle
    #[test]
    fn test_mmap_create_and_reopen() {
        let path = tmp_path("test_mmap_create_and_reopen.nxr");
        cleanup(&path);

        {
            let store = MmapStore::create(&path).unwrap();
            let mut manager = StorageManager::from_page_store(store).unwrap();
            manager.close().unwrap();
        }

        let store = MmapStore::open(&path).unwrap();
        let manager = StorageManager::from_page_store(store).unwrap();

        assert_eq!(&manager.header.magic, b"NXRA");
        assert_eq!(manager.header.version.get(), 1);

        cleanup(&path);
    }

    // Test 2 — page I/O round trip: write bytes, read them back
    #[test]
    fn test_mmap_page_io_round_trip() {
        let path = tmp_path("test_mmap_page_io_round_trip.nxr");
        cleanup(&path);

        let store = MmapStore::create(&path).unwrap();
        let mut manager = StorageManager::from_page_store(store).unwrap();

        let page_id = manager.allocate_page().unwrap();

        let mut write_buf = [0u8; PAGE_SIZE];
        write_buf[0..5].copy_from_slice(b"hello");
        write_buf[PAGE_SIZE - 1] = 0xFF;

        manager.store.write_page(page_id, &write_buf, true).unwrap();

        let mut read_buf = [0u8; PAGE_SIZE];
        manager.store.read_page(page_id, &mut read_buf, true).unwrap();

        assert_eq!(&read_buf[0..5], b"hello");
        assert_eq!(read_buf[PAGE_SIZE - 1], 0xFF);

        cleanup(&path);
    }

    // Test 3 — checksum mismatch: corrupted byte is detected on read
    #[test]
    fn test_mmap_checksum_mismatch() {
        let path = tmp_path("test_mmap_checksum_mismatch.nxr");
        cleanup(&path);

        {
            let store = MmapStore::create(&path).unwrap();
            let mut manager = StorageManager::from_page_store(store).unwrap();
            let page_id = manager.allocate_page().unwrap();
            let buf = [0xABu8; PAGE_SIZE];
            manager.store.write_page(page_id, &buf, true).unwrap();
            manager.close().unwrap();

            let mut file = std::fs::OpenOptions::new().write(true).open(&path).unwrap();
            use std::io::{Seek, Write};
            file.seek(std::io::SeekFrom::Start(page_id.byte_offset() + 100)).unwrap();
            file.write_all(&[0x00]).unwrap();
        }

        let store = MmapStore::open(&path).unwrap();
        let mut manager = StorageManager::from_page_store(store).unwrap();
        let mut buf = [0u8; PAGE_SIZE];
        let result = manager.store.read_page(PageId(2), &mut buf, true);

        assert!(matches!(result, Err(NexoraStorageError::ChecksumMismatch(_))));

        cleanup(&path);
    }

    // Test 4 — footer persistence: page_count survives close/reopen
    #[test]
    fn test_mmap_footer_persistence() {
        let path = tmp_path("test_mmap_footer_persistence.nxr");
        cleanup(&path);

        {
            let store = MmapStore::create(&path).unwrap();
            let mut manager = StorageManager::from_page_store(store).unwrap();
            manager.allocate_page().unwrap();
            manager.allocate_page().unwrap();
            manager.allocate_page().unwrap();
            manager.close().unwrap();
        }

        let store = MmapStore::open(&path).unwrap();
        let manager = StorageManager::from_page_store(store).unwrap();

        // started at 2 (header + footer), allocated 3 more
        assert_eq!(manager.footer.page_count.get(), 5);

        cleanup(&path);
    }

    // Test 5 — file growth: writing beyond the initial GROW_PAGES mapping remaps correctly
    #[test]
    fn test_mmap_file_growth() {
        let path = tmp_path("test_mmap_file_growth.nxr");
        cleanup(&path);

        let store = MmapStore::create(&path).unwrap();
        let mut manager = StorageManager::from_page_store(store).unwrap();

        // GROW_PAGES = 64; allocate enough pages to exceed the initial mapping.
        // Pages 0 and 1 are header/footer, so allocate 63 more to reach page 64.
        for _ in 0..63 {
            manager.allocate_page().unwrap();
        }

        // Write and read back the page that triggered the remap (page 64)
        let last_page = manager.allocate_page().unwrap();
        assert_eq!(last_page.as_u64(), 65); // 0..1 reserved + 63 + 1

        let mut write_buf = [0u8; PAGE_SIZE];
        write_buf[0..6].copy_from_slice(b"growth");
        manager.store.write_page(last_page, &write_buf, true).unwrap();

        let mut read_buf = [0u8; PAGE_SIZE];
        manager.store.read_page(last_page, &mut read_buf, true).unwrap();

        assert_eq!(&read_buf[0..6], b"growth");

        cleanup(&path);
    }
}

use core::result::Result;
use zerocopy::{FromBytes, IntoBytes};

use crate::storage::page_store::PageStore;
use crate::storage::models::{INITIAL_FOOTER, INITIAL_HEADER, NexoraPageHeader, PageId};
use crate::storage::constants::{PAGE_HEADER_SIZE, PAGE_SIZE};
use crate::storage::error::NexoraStorageError;

// Grow the file in 64-page (256 KB) chunks to amortise the cost of remapping.
const GROW_PAGES: u64 = 64;

// AI_GENERATED: Generated by AI (CLAUDE_CODE)
pub struct MmapStore {
    file: std::fs::File,
    mmap: memmap2::MmapMut,
    file_pages: u64,
}

impl MmapStore {
    pub fn create(path: &std::path::Path) -> Result<Self, NexoraStorageError> {
        let file = std::fs::OpenOptions::new()
            .read(true)
            .write(true)
            .create_new(true)
            .open(path)?;

        file.set_len(GROW_PAGES * PAGE_SIZE as u64)?;
        // SAFETY: Nexora is single-writer; no other process modifies the file concurrently.
        let mmap = unsafe { memmap2::MmapMut::map_mut(&file) }?;
        let mut store = MmapStore { file, mmap, file_pages: GROW_PAGES };
        store.write_default_header()?;
        store.write_default_footer()?;
        Ok(store)
    }

    pub fn open(path: &std::path::Path) -> Result<Self, NexoraStorageError> {
        let file = std::fs::OpenOptions::new()
            .read(true)
            .write(true)
            .open(path)?;

        let file_pages = file.metadata()?.len() / PAGE_SIZE as u64;
        // SAFETY: Nexora is single-writer; no other process modifies the file concurrently.
        let mmap = unsafe { memmap2::MmapMut::map_mut(&file) }?;
        Ok(MmapStore { file, mmap, file_pages })
    }

    fn write_default_header(&mut self) -> Result<(), NexoraStorageError> {
        self.write_page(PageId(0), INITIAL_HEADER.as_bytes().try_into().expect("INITIAL_HEADER is PAGE_SIZE"), true)
    }

    fn write_default_footer(&mut self) -> Result<(), NexoraStorageError> {
        self.write_page(PageId(1), INITIAL_FOOTER.as_bytes().try_into().expect("INITIAL_FOOTER is PAGE_SIZE"), true)
    }

    fn grow(&mut self, min_pages: u64) -> Result<(), NexoraStorageError> {
        let new_pages = ((min_pages + GROW_PAGES - 1) / GROW_PAGES) * GROW_PAGES;
        self.mmap.flush()?;
        // Replace the mapping with a 1-byte anonymous placeholder so the file
        // has no active mappings before set_len. On Windows, SetEndOfFile fails
        // with ERROR_USER_MAPPED_FILE if any mapping of the file is still open.
        // SAFETY: &mut self guarantees no live references into the old mapping.
        let old = std::mem::replace(
            &mut self.mmap,
            memmap2::MmapOptions::new().len(1).map_anon()?,
        );
        drop(old);
        self.file.set_len(new_pages * PAGE_SIZE as u64)?;
        self.mmap = unsafe { memmap2::MmapMut::map_mut(&self.file) }?;
        self.file_pages = new_pages;
        Ok(())
    }
}

impl PageStore for MmapStore {
    fn read_page(&mut self, page_id: PageId, buf: &mut [u8; PAGE_SIZE], verify_checksum: bool) -> Result<(), NexoraStorageError> {
        let offset = page_id.byte_offset() as usize;
        buf.copy_from_slice(&self.mmap[offset..offset + PAGE_SIZE]);
        let stored = Self::get_checksum(buf);
        if verify_checksum && !Self::verify_checksum(buf, stored) {
            return Err(NexoraStorageError::ChecksumMismatch(page_id.as_u64()));
        }
        Ok(())
    }

    fn write_page(&mut self, page_id: PageId, buf: &[u8; PAGE_SIZE], stamp_checksum: bool) -> Result<(), NexoraStorageError> {
        if page_id.as_u64() >= self.file_pages {
            self.grow(page_id.as_u64() + 1)?;
        }
        let mut page = *buf;
        if stamp_checksum {
            Self::stamp_checksum(&mut page);
        }
        let offset = page_id.byte_offset() as usize;
        self.mmap[offset..offset + PAGE_SIZE].copy_from_slice(&page);
        Ok(())
    }

    fn read_page_header_unchecked(&mut self, page_id: PageId) -> Result<NexoraPageHeader, NexoraStorageError> {
        let offset = page_id.byte_offset() as usize;
        let header = NexoraPageHeader::ref_from_bytes(&self.mmap[offset..offset + PAGE_HEADER_SIZE])
            .map_err(|_| NexoraStorageError::CorruptPage(page_id.as_u64()))?;
        Ok(*header)
    }

    fn sync(&mut self) -> Result<(), NexoraStorageError> {
        self.mmap.flush().map_err(Into::into)
    }

    fn close(&mut self) -> Result<(), NexoraStorageError> {
        self.mmap.flush().map_err(Into::into)
    }
}
