// AI_GENERATED: Generated by AI (CLAUDE_CODE)
 
#[cfg(test)]
mod tests {
    use crate::storage::storage_manager::StorageManager;
    use crate::storage::page_store_disk::RegularPageStore;
    use crate::storage::error::NexoraStorageError;
    use crate::storage::models::PageId;
    use crate::storage::constants::PAGE_SIZE;
    use crate::storage::page_store::PageStore;
    use std::io::Write;
    use std::path::PathBuf;

    fn tmp_path(name: &str) -> PathBuf {
        std::env::temp_dir().join(name)
    }

    fn cleanup(path: &PathBuf) {
        let _ = std::fs::remove_file(path);
    }

    // Test 1 — create and reopen: header survives close/reopen cycle
    #[test]
    fn test_create_and_reopen() {
        let path = tmp_path("test_create_and_reopen.nxra");
        cleanup(&path);

        {
            let store = RegularPageStore::create(&path).unwrap();
            let mut manager = StorageManager::from_page_store(store).unwrap();
            manager.close().unwrap();
        }

        let store = RegularPageStore::open(&path).unwrap();
        let manager = StorageManager::from_page_store(store).unwrap();

        assert_eq!(&manager.header.magic, b"NXRA");
        assert_eq!(manager.header.version.get(), 1);

        cleanup(&path);
    }

    // Test 2 — page I/O round trip: write bytes, read them back
    #[test]
    fn test_page_io_round_trip() {
        let path = tmp_path("test_page_io_round_trip.nxra");
        cleanup(&path);

        let store = RegularPageStore::create(&path).unwrap();
        let mut manager = StorageManager::from_page_store(store).unwrap();

        let page_id = manager.allocate_page().unwrap();

        let mut write_buf = [0u8; PAGE_SIZE];
        write_buf[0..5].copy_from_slice(b"hello");
        write_buf[PAGE_SIZE - 1] = 0xFF;

        manager.store.write_page(page_id, &write_buf, true).unwrap();

        let mut read_buf = [0u8; PAGE_SIZE];
        manager.store.read_page(page_id, &mut read_buf, true).unwrap();

        assert_eq!(&read_buf[0..5], b"hello");
        assert_eq!(read_buf[PAGE_SIZE - 1], 0xFF);

        cleanup(&path);
    }

    // Test 3 — checksum mismatch: corrupted page is detected
    #[test]
    fn test_checksum_mismatch() {
        let path = tmp_path("test_checksum_mismatch.nxra");
        cleanup(&path);

        {
            let store = RegularPageStore::create(&path).unwrap();
            let mut manager = StorageManager::from_page_store(store).unwrap();
            let page_id = manager.allocate_page().unwrap();
            let buf = [0xABu8; PAGE_SIZE];
            manager.store.write_page(page_id, &buf, true).unwrap();
            manager.close().unwrap();

            // corrupt a byte directly in the file after the checksum field
            let mut file = std::fs::OpenOptions::new().write(true).open(&path).unwrap();
            let corrupt_offset = page_id.byte_offset() + 100;
            use std::io::Seek;
            file.seek(std::io::SeekFrom::Start(corrupt_offset)).unwrap();
            file.write_all(&[0x00]).unwrap();
        }

        let store = RegularPageStore::open(&path).unwrap();
        let mut manager = StorageManager::from_page_store(store).unwrap();
        let page_id = PageId(2);
        let mut buf = [0u8; PAGE_SIZE];
        let result = manager.store.read_page(page_id, &mut buf, true);

        assert!(matches!(result, Err(NexoraStorageError::ChecksumMismatch(_))));

        cleanup(&path);
    }

    // Test 4 — free list round trip: freed pages are reused before growing
    #[test]
    fn test_free_list_round_trip() {
        let path = tmp_path("test_free_list_round_trip.nxra");
        cleanup(&path);

        let store = RegularPageStore::create(&path).unwrap();
        let mut manager = StorageManager::from_page_store(store).unwrap();

        let p2 = manager.allocate_page().unwrap();
        let p3 = manager.allocate_page().unwrap();
        let p4 = manager.allocate_page().unwrap();

        assert_eq!(p2.as_u64(), 2);
        assert_eq!(p3.as_u64(), 3);
        assert_eq!(p4.as_u64(), 4);

        let page_count_before = manager.footer.page_count.get();

        manager.free_page(p3).unwrap();

        let reused = manager.allocate_page().unwrap();
        assert_eq!(reused.as_u64(), 3);
        assert_eq!(manager.footer.page_count.get(), page_count_before);

        cleanup(&path);
    }

    // Test 5 — footer persistence: page_count survives close/reopen
    #[test]
    fn test_footer_persistence() {
        let path = tmp_path("test_footer_persistence.nxra");
        cleanup(&path);

        {
            let store = RegularPageStore::create(&path).unwrap();
            let mut manager = StorageManager::from_page_store(store).unwrap();
            manager.allocate_page().unwrap();
            manager.allocate_page().unwrap();
            manager.allocate_page().unwrap();
            manager.close().unwrap();
        }

        let store = RegularPageStore::open(&path).unwrap();
        let manager = StorageManager::from_page_store(store).unwrap();

        // started at 2 (header + footer), allocated 3 more
        assert_eq!(manager.footer.page_count.get(), 5);

        cleanup(&path);
    }
}
