// AI_GENERATED: Generated by AI (CLAUDE_CODE)
#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use crate::storage::constants::PAGE_SIZE;
    use crate::storage::error::NexoraStorageError;
    use crate::storage::models::PageId;
    use crate::storage::page_store::PageStore;
    use crate::storage::page_store_disk::RegularPageStore;
    use crate::storage::wal::models::{WALHeader, WALPageStore};

    fn tmp(name: &str) -> PathBuf {
        std::env::temp_dir().join(name)
    }

    fn paths(name: &str) -> (PathBuf, PathBuf) {
        (tmp(&format!("{}.nxr", name)), tmp(&format!("{}.nxr-wal", name)))
    }

    fn cleanup(db: &PathBuf, wal: &PathBuf) {
        let _ = std::fs::remove_file(db);
        let _ = std::fs::remove_file(wal);
    }

    // Test 1 — write then read from WAL: data comes from WAL, not main file
    #[test]
    fn test_wal_write_read_round_trip() {
        let (db, wal) = paths("test_wal_write_read_round_trip");
        cleanup(&db, &wal);

        let inner = RegularPageStore::create(&db).unwrap();
        let mut store = WALPageStore::create(inner, &wal).unwrap();

        let mut page = [0u8; PAGE_SIZE];
        page[0..5].copy_from_slice(b"hello");
        store.write_page(PageId(2), &page, false).unwrap();

        let mut buf = [0u8; PAGE_SIZE];
        store.read_page(PageId(2), &mut buf, false).unwrap();

        assert_eq!(&buf[0..5], b"hello");
        cleanup(&db, &wal);
    }

    // Test 2 — read falls through to inner: page not in WAL comes from main file
    #[test]
    fn test_wal_read_falls_through_to_inner() {
        let (db, wal) = paths("test_wal_read_falls_through_to_inner");
        cleanup(&db, &wal);

        let inner = RegularPageStore::create(&db).unwrap();
        let mut store = WALPageStore::create(inner, &wal).unwrap();

        // Page 0 is the main file header — never written to WAL.
        // Falls through to inner which holds the "NXRA" header written at create time.
        let mut buf = [0u8; PAGE_SIZE];
        store.read_page(PageId(0), &mut buf, false).unwrap();

        // NexoraHeader.magic is at byte offset 48 (page_header:32 + version:4 + page_size:4 + footer_page_id:8)
        assert_eq!(&buf[48..52], b"NXRA");
        cleanup(&db, &wal);
    }

    // Test 3 — latest write wins: second write to same page_id updates the index entry
    #[test]
    fn test_wal_latest_write_wins() {
        let (db, wal) = paths("test_wal_latest_write_wins");
        cleanup(&db, &wal);

        let inner = RegularPageStore::create(&db).unwrap();
        let mut store = WALPageStore::create(inner, &wal).unwrap();

        let mut page = [0u8; PAGE_SIZE];
        page[0..5].copy_from_slice(b"first");
        store.write_page(PageId(2), &page, false).unwrap();

        page[0..6].copy_from_slice(b"second");
        store.write_page(PageId(2), &page, false).unwrap();

        let mut buf = [0u8; PAGE_SIZE];
        store.read_page(PageId(2), &mut buf, false).unwrap();

        assert_eq!(&buf[0..6], b"second");
        cleanup(&db, &wal);
    }

    // Test 4 — checkpoint writes pages to main file and clears WAL
    #[test]
    fn test_wal_checkpoint() {
        let (db, wal) = paths("test_wal_checkpoint");
        cleanup(&db, &wal);

        {
            let inner = RegularPageStore::create(&db).unwrap();
            let mut store = WALPageStore::create(inner, &wal).unwrap();

            let mut page = [0u8; PAGE_SIZE];
            page[0..5].copy_from_slice(b"hello");
            store.write_page(PageId(2), &page, false).unwrap();
            store.commit().unwrap();
            store.checkpoint().unwrap();
        }

        // WAL file should be exactly the header size — all frames cleared.
        let wal_size = std::fs::metadata(&wal).unwrap().len();
        assert_eq!(wal_size as usize, std::mem::size_of::<WALHeader>());

        // Main file should have the page.
        let mut inner = RegularPageStore::open(&db).unwrap();
        let mut buf = [0u8; PAGE_SIZE];
        inner.read_page(PageId(2), &mut buf, false).unwrap();
        assert_eq!(&buf[0..5], b"hello");

        cleanup(&db, &wal);
    }

    // Test 5 — close triggers checkpoint: data survives in main file after close
    #[test]
    fn test_wal_close_checkpoints() {
        let (db, wal) = paths("test_wal_close_checkpoints");
        cleanup(&db, &wal);

        {
            let inner = RegularPageStore::create(&db).unwrap();
            let mut store = WALPageStore::create(inner, &wal).unwrap();

            let mut page = [0u8; PAGE_SIZE];
            page[0..6].copy_from_slice(b"nexora");
            store.write_page(PageId(2), &page, false).unwrap();
            store.commit().unwrap();
            store.close().unwrap();
        }

        let mut inner = RegularPageStore::open(&db).unwrap();
        let mut buf = [0u8; PAGE_SIZE];
        inner.read_page(PageId(2), &mut buf, false).unwrap();
        assert_eq!(&buf[0..6], b"nexora");

        cleanup(&db, &wal);
    }

    // Test 6 — recovery replays committed frames: open after crash (no close) restores data
    #[test]
    fn test_wal_recovery_replays_committed() {
        let (db, wal) = paths("test_wal_recovery_replays_committed");
        cleanup(&db, &wal);

        // Write and commit but drop without calling close — simulates crash after commit.
        {
            let inner = RegularPageStore::create(&db).unwrap();
            let mut store = WALPageStore::create(inner, &wal).unwrap();

            let mut page = [0u8; PAGE_SIZE];
            page[0..5].copy_from_slice(b"crash");
            store.write_page(PageId(2), &page, false).unwrap();
            store.commit().unwrap();
            // Dropped here — no checkpoint, WAL has the committed frame.
        }

        // Reopen — recovery scans the WAL and rebuilds the index.
        let inner = RegularPageStore::open(&db).unwrap();
        let mut store = WALPageStore::open(inner, &wal).unwrap();

        let mut buf = [0u8; PAGE_SIZE];
        store.read_page(PageId(2), &mut buf, false).unwrap();
        assert_eq!(&buf[0..5], b"crash");

        cleanup(&db, &wal);
    }

    // Test 7 — recovery discards uncommitted frames: crash before commit loses the write
    #[test]
    fn test_wal_recovery_discards_uncommitted() {
        let (db, wal) = paths("test_wal_recovery_discards_uncommitted");
        cleanup(&db, &wal);

        // Write but do NOT commit — drop simulates crash mid-transaction.
        {
            let inner = RegularPageStore::create(&db).unwrap();
            let mut store = WALPageStore::create(inner, &wal).unwrap();

            let mut page = [0u8; PAGE_SIZE];
            page[0..4].copy_from_slice(b"oops");
            store.write_page(PageId(2), &page, false).unwrap();
            // No commit.
        }

        // Reopen — uncommitted frame is discarded, page 2 is not in the index.
        let inner = RegularPageStore::open(&db).unwrap();
        let mut store = WALPageStore::open(inner, &wal).unwrap();

        // Page 2 falls through to inner which has no page 2 — expect I/O error.
        let mut buf = [0u8; PAGE_SIZE];
        let result = store.read_page(PageId(2), &mut buf, false);
        assert!(matches!(result, Err(NexoraStorageError::Io(_))));

        cleanup(&db, &wal);
    }

    // Test 8 — corrupt WAL header magic: open returns InvalidMagicBytes
    #[test]
    fn test_wal_corrupt_header_magic() {
        let (db, wal) = paths("test_wal_corrupt_header_magic");
        cleanup(&db, &wal);

        // Write a valid-size header with wrong magic.
        std::fs::write(&wal, b"BADMAGIC????????").unwrap();

        let inner = RegularPageStore::create(&db).unwrap();
        let result = WALPageStore::open(inner, &wal);

        assert!(matches!(result, Err(NexoraStorageError::InvalidMagicBytes)));
        cleanup(&db, &wal);
    }

    // Test 9 — multiple pages survive checkpoint: each page written to correct location
    #[test]
    fn test_wal_multiple_pages_checkpoint() {
        let (db, wal) = paths("test_wal_multiple_pages_checkpoint");
        cleanup(&db, &wal);

        {
            let inner = RegularPageStore::create(&db).unwrap();
            let mut store = WALPageStore::create(inner, &wal).unwrap();

            for i in 2u64..7 {
                let mut page = [0u8; PAGE_SIZE];
                page[0] = i as u8;
                store.write_page(PageId(i), &page, false).unwrap();
            }
            store.commit().unwrap();
            store.close().unwrap();
        }

        let mut inner = RegularPageStore::open(&db).unwrap();
        for i in 2u64..7 {
            let mut buf = [0u8; PAGE_SIZE];
            inner.read_page(PageId(i), &mut buf, false).unwrap();
            assert_eq!(buf[0], i as u8, "page {} data mismatch after checkpoint", i);
        }

        cleanup(&db, &wal);
    }

    // Test 10 — read_page_header_unchecked from WAL: returns header from WAL frame
    #[test]
    fn test_wal_read_page_header_unchecked() {
        let (db, wal) = paths("test_wal_read_page_header_unchecked");
        cleanup(&db, &wal);

        let inner = RegularPageStore::create(&db).unwrap();
        let mut store = WALPageStore::create(inner, &wal).unwrap();

        // Page 0 is in inner, not WAL — falls through to inner.
        let header = store.read_page_header_unchecked(PageId(0)).unwrap();
        assert_eq!(header.page_id.get(), 0);

        // Write a page to WAL and read its header back.
        let mut page = [0u8; PAGE_SIZE];
        page[0..8].copy_from_slice(&42u64.to_le_bytes()); // page_id field
        store.write_page(PageId(2), &page, false).unwrap();

        let header = store.read_page_header_unchecked(PageId(2)).unwrap();
        assert_eq!(header.page_id.get(), 42);

        cleanup(&db, &wal);
    }
}
