use core::result::Result;
use zerocopy::FromBytes;

use crate::buffer_pool::constants::{BUFFER_POOL_MAX_PAGE_COUNT, BUFFER_POOL_WORD_COUNT};

use crate::storage::constants::{PAGE_HEADER_SIZE, PAGE_SIZE, SENTINEL_PAGE_ID};
use crate::storage::models::{NexoraPageHeader, PageId};
use crate::storage::page_store::PageStore;
use crate::storage::error::NexoraStorageError;

use crate::utils::containers::bitsets::BitSet64;

#[derive(Debug, Copy, Clone)]
#[repr(align(4096))]
pub struct Frame {
    page: [u8; PAGE_SIZE],
}


// NOTE: should be called only inside the main
#[derive(Debug)]
pub struct BufferStore<S: PageStore> {
    frames:     Box<[Frame]>,
    page_ids:   Box<[PageId]>,
    dirty_bits: BitSet64<BUFFER_POOL_WORD_COUNT>,
    ref_bits:   BitSet64<BUFFER_POOL_WORD_COUNT>,
    clock_hand: usize,
    store:      S,
}

impl<S: PageStore> BufferStore<S> {

    pub fn new(store: S) -> Self {
        Self {
            frames:     vec![Frame { page: [0u8; PAGE_SIZE] }; BUFFER_POOL_MAX_PAGE_COUNT].into_boxed_slice(),
            page_ids:   vec![PageId(SENTINEL_PAGE_ID); BUFFER_POOL_MAX_PAGE_COUNT].into_boxed_slice(),
            dirty_bits: BitSet64::EMPTY,
            ref_bits:   BitSet64::EMPTY,
            clock_hand: 0,
            store,
        }
    }

    // @TODO: If the buffer size grows or is dynamically configured move away from linear search.
    fn find_frame(&self, page_id: PageId) -> Option<usize> {
        self.page_ids.iter().position(|id| *id == page_id)
    }

    fn flush(&mut self) -> Result<(), NexoraStorageError> {
        while let Some(i) = self.dirty_bits.first_set() {
            self.flush_frame(i)?;
        }
        Ok(())
    }

    fn flush_frame(&mut self, frame_idx: usize) -> Result<(), NexoraStorageError> {
        let page_id = self.page_ids[frame_idx];
        let data = self.frames[frame_idx].page;
        self.store.write_page(page_id, &data, true)?;
        self.dirty_bits.clear(frame_idx);
        Ok(())
    }

    fn evict(&mut self) -> Result<usize, NexoraStorageError> {
        loop {
            let i = self.clock_hand % BUFFER_POOL_MAX_PAGE_COUNT;
            self.clock_hand += 1;

            if self.ref_bits.get(i) {
                self.ref_bits.clear(i);
            } else {
                if self.dirty_bits.get(i) {
                    self.flush_frame(i)?;
                }
                return Ok(i);
            }
        }
    }

    fn insert_cache(&mut self, page_id: PageId) -> Result<usize, NexoraStorageError> {
        let i = self.evict()?;
        let mut buf = [0u8; PAGE_SIZE];
        self.store.read_page(page_id, &mut buf, false)?;
        self.frames[i].page = buf;
        self.page_ids[i] = page_id;
        self.ref_bits.set(i);
        self.dirty_bits.clear(i);
        Ok(i)
    }

}

impl<S: PageStore> PageStore for BufferStore<S> {
    fn read_page(&mut self, page_id: PageId, buf: &mut [u8; PAGE_SIZE], _verify_checksum: bool) -> core::result::Result<(), NexoraStorageError> {
        let i = match self.find_frame(page_id) {
            Some(i) => {
                self.ref_bits.set(i);
                i
            }
            None => self.insert_cache(page_id)?,
        };
        *buf = self.frames[i].page;
        Ok(())
    }

    fn write_page(&mut self, page_id: PageId, buf: &[u8; PAGE_SIZE], _stamp_checksum: bool) -> core::result::Result<(), NexoraStorageError> {
        let i = match self.find_frame(page_id) {
            Some(i) => i,
            None => {
                let i = self.evict()?;
                self.page_ids[i] = page_id;
                i
            }
        };
        self.frames[i].page = *buf;
        self.dirty_bits.set(i);
        self.ref_bits.set(i);
        Ok(())
    }

    fn close(&mut self) -> core::result::Result<(), NexoraStorageError> {
        self.flush()?;
        self.store.close()
    }

    // AI_GENERATED: Generated by AI (CLAUDE_CODE)
    fn read_page_header_unchecked(&mut self, page_id: PageId) -> core::result::Result<NexoraPageHeader, NexoraStorageError> {
        let i = match self.find_frame(page_id) {
            Some(i) => {
                self.ref_bits.set(i);
                i
            }
            None => self.insert_cache(page_id)?,
        };
        let header = NexoraPageHeader::ref_from_bytes(&self.frames[i].page[..PAGE_HEADER_SIZE])
            .map_err(|_| NexoraStorageError::CorruptPage(page_id.as_u64()))?;
        Ok(*header)
    }
}
