// AI_GENERATED: Generated by AI (CLAUDE_CODE)

#[cfg(test)]
mod tests {
    use crate::buffer_pool::models::BufferStore;
    use crate::storage::page_store_disk::RegularPageStore;
    use crate::storage::storage_manager::StorageManager;
    use crate::storage::page_store::PageStore;
    use crate::storage::constants::PAGE_SIZE;
    use crate::storage::models::PageId;
    use std::path::PathBuf;

    const LARGE_STACK: usize = 16 * 1024 * 1024; // 16 MB — accommodates 1 MB BufferStore on stack

    fn tmp_path(name: &str) -> PathBuf {
        std::env::temp_dir().join(name)
    }

    fn cleanup(path: &PathBuf) {
        let _ = std::fs::remove_file(path);
    }

    fn run<F: FnOnce() + Send + 'static>(f: F) {
        std::thread::Builder::new()
            .stack_size(LARGE_STACK)
            .spawn(f)
            .unwrap()
            .join()
            .unwrap();
    }

    fn create_buffered(path: &PathBuf) -> StorageManager<BufferStore<RegularPageStore>> {
        let store = RegularPageStore::create(path).unwrap();
        StorageManager::from_page_store(BufferStore::new(store)).unwrap()
    }

    fn open_buffered(path: &PathBuf) -> StorageManager<BufferStore<RegularPageStore>> {
        let store = RegularPageStore::open(path).unwrap();
        StorageManager::from_page_store(BufferStore::new(store)).unwrap()
    }

    fn open_direct(path: &PathBuf) -> StorageManager<RegularPageStore> {
        let store = RegularPageStore::open(path).unwrap();
        StorageManager::from_page_store(store).unwrap()
    }

    // Test 1 — write then read returns correct data from cache
    #[test]
    fn test_write_read_roundtrip() {
        let path = tmp_path("buf_test_write_read.nxr");
        cleanup(&path);
        run(move || {
            let mut manager = create_buffered(&path);
            let page_id = manager.allocate_page().unwrap();

            let mut write_buf = [0u8; PAGE_SIZE];
            write_buf[0..5].copy_from_slice(b"hello");
            write_buf[PAGE_SIZE - 1] = 0xAB;
            manager.store.write_page(page_id, &write_buf, false).unwrap();

            let mut read_buf = [0u8; PAGE_SIZE];
            manager.store.read_page(page_id, &mut read_buf, false).unwrap();

            assert_eq!(&read_buf[0..5], b"hello");
            assert_eq!(read_buf[PAGE_SIZE - 1], 0xAB);

            cleanup(&path);
        });
    }

    // Test 2 — dirty pages are flushed to disk on close
    #[test]
    fn test_dirty_flush_on_close() {
        let path = tmp_path("buf_test_flush.nxr");
        cleanup(&path);
        run(move || {
            let page_id: PageId = {
                let mut manager = create_buffered(&path);
                let page_id = manager.allocate_page().unwrap();

                let mut buf = [0u8; PAGE_SIZE];
                buf[0..6].copy_from_slice(b"flushy");
                manager.store.write_page(page_id, &buf, false).unwrap();
                manager.close().unwrap();
                page_id
            };

            let mut manager = open_direct(&path);
            let mut read_buf = [0u8; PAGE_SIZE];
            manager.store.read_page(page_id, &mut read_buf, false).unwrap();

            assert_eq!(&read_buf[0..6], b"flushy");

            cleanup(&path);
        });
    }

    // Test 3 — cache miss on fresh open loads page from disk
    #[test]
    fn test_cache_miss_loads_from_disk() {
        let path = tmp_path("buf_test_cache_miss.nxr");
        cleanup(&path);
        run(move || {
            let page_id: PageId = {
                let mut manager = create_buffered(&path);
                let page_id = manager.allocate_page().unwrap();

                let mut buf = [0u8; PAGE_SIZE];
                buf[0..4].copy_from_slice(b"disk");
                manager.store.write_page(page_id, &buf, false).unwrap();
                manager.close().unwrap();
                page_id
            };

            let mut manager = open_buffered(&path);
            let mut read_buf = [0u8; PAGE_SIZE];
            manager.store.read_page(page_id, &mut read_buf, false).unwrap();

            assert_eq!(&read_buf[0..4], b"disk");

            cleanup(&path);
        });
    }

    // Test 4 — multiple pages coexist in cache correctly
    #[test]
    fn test_multiple_pages_in_cache() {
        let path = tmp_path("buf_test_multi.nxr");
        cleanup(&path);
        run(move || {
            let mut manager = create_buffered(&path);
            let mut page_ids = [PageId(0); 8];

            for i in 0..8usize {
                let page_id = manager.allocate_page().unwrap();
                let mut buf = [0u8; PAGE_SIZE];
                buf[0] = i as u8;
                buf[1] = (i as u8).wrapping_mul(7);
                manager.store.write_page(page_id, &buf, false).unwrap();
                page_ids[i] = page_id;
            }

            for i in (0..8usize).rev() {
                let mut buf = [0u8; PAGE_SIZE];
                manager.store.read_page(page_ids[i], &mut buf, false).unwrap();
                assert_eq!(buf[0], i as u8);
                assert_eq!(buf[1], (i as u8).wrapping_mul(7));
            }

            cleanup(&path);
        });
    }

    // Test 5 — overwrite same page, latest write wins
    #[test]
    fn test_overwrite_page() {
        let path = tmp_path("buf_test_overwrite.nxr");
        cleanup(&path);
        run(move || {
            let mut manager = create_buffered(&path);
            let page_id = manager.allocate_page().unwrap();

            manager.store.write_page(page_id, &[0xAAu8; PAGE_SIZE], false).unwrap();
            manager.store.write_page(page_id, &[0xBBu8; PAGE_SIZE], false).unwrap();

            let mut read_buf = [0u8; PAGE_SIZE];
            manager.store.read_page(page_id, &mut read_buf, false).unwrap();

            assert!(read_buf.iter().all(|&b| b == 0xBB));

            cleanup(&path);
        });
    }
}
