// AI_GENERATED: Generated by AI (CLAUDE_CODE)
use thiserror::Error;

use crate::graph::node::error::NexoraGraphNodeError;
use crate::graph::edge::error::NexoraGraphEdgeError;
use crate::graph::label::error::NexoraGraphLabelError;
use crate::graph::property::error::NexoraGraphPropertyError;
use crate::graph::string::error::NexoraGraphStringError;
use crate::storage::error::NexoraStorageError;

#[derive(Debug, Error)]
pub enum NexoraGraphStoreError {
    #[error("Node error: {0}")]
    Node(#[from] NexoraGraphNodeError),

    #[error("Edge error: {0}")]
    Edge(#[from] NexoraGraphEdgeError),

    #[error("Label error: {0}")]
    Label(#[from] NexoraGraphLabelError),

    #[error("Property error: {0}")]
    Property(#[from] NexoraGraphPropertyError),

    #[error("String error: {0}")]
    Str(#[from] NexoraGraphStringError),

    #[error("Storage error: {0}")]
    Storage(#[from] NexoraStorageError),

    #[error("Label is not valid UTF-8")]
    InvalidUtf8,
}
