// AI_GENERATED: Generated by AI (CLAUDE_CODE)
use crate::graph::edge::graph_edge_store::GraphEdgeStore;
use crate::graph::edge::page::GraphEdgeRecord;
use crate::graph::graphstore::error::NexoraGraphStoreError;
use crate::graph::label::constants::MAX_LABEL_LENGTH;
use crate::graph::label::graph_label_store::LabelStore;
use crate::graph::models::{Edge, Node, Property};
use crate::graph::string::constants::MAX_STRING_LENGTH;
use crate::graph::node::graph_node_store::GraphNodeStore;
use crate::graph::property::graph_property_store::PropertyStore;
use crate::graph::record::types::{PackedPtr, RecordCursor};
use crate::graph::string::graph_string_store::StringStore;
use crate::storage::page_store::PageStore;
use crate::storage::storage_manager::StorageManager;


pub struct GraphStore<S: PageStore> {
    storage: StorageManager<S>,
}

impl<S: PageStore> GraphStore<S> {
    pub fn new(storage: StorageManager<S>) -> Self {
        GraphStore { storage }
    }

    pub fn close(&mut self) -> Result<(), NexoraGraphStoreError> {
        Ok(self.storage.close()?)
    }

    // --- Nodes ---

    pub fn insert_node(&mut self, label: &str) -> Result<u64, NexoraGraphStoreError> {
        let label_id = {
            let mut ls = LabelStore::new(&mut self.storage);
            ls.insert_label(label.as_bytes())?
        };
        let mut ns = GraphNodeStore::new(&mut self.storage);
        Ok(ns.insert_node(label_id, PackedPtr::NULL)?)
    }

    pub fn get_node(&mut self, node_id: u64) -> Result<Node, NexoraGraphStoreError> {
        let record = {
            let mut ns = GraphNodeStore::new(&mut self.storage);
            ns.get_node(node_id)?
        };
        let label = self.resolve_label(record.label_id.get())?;
        Ok(Node { id: node_id, label })
    }

    pub fn update_node(&mut self, node: &Node) -> Result<(), NexoraGraphStoreError> {
        let label_id = {
            let mut ls = LabelStore::new(&mut self.storage);
            ls.insert_label(node.label.as_bytes())?
        };
        let mut ns = GraphNodeStore::new(&mut self.storage);
        Ok(ns.update_label(node.id, label_id)?)
    }

    pub fn delete_node(&mut self, node_id: u64) -> Result<(), NexoraGraphStoreError> {
        // Delete outgoing edges. The cursor captures next_outgoing before we call delete_edge,
        // so chain modifications from delete_edge never affect the cursor's next pointer.
        let mut cursor = {
            let mut es = GraphEdgeStore::new(&mut self.storage);
            es.outgoing_cursor(node_id)?
        };
        loop {
            let record = {
                let mut es = GraphEdgeStore::new(&mut self.storage);
                es.cursor_next_outgoing(&mut cursor)?
            };

            match record {
                None => break,
                Some(r) => self.delete_edge(r.edge_id())?,
            }
        }

        // Delete incoming edges. Self-loops were already removed from the incoming chain by
        // delete_edge above, so this pass never encounters a double-delete.
        let mut cursor = {
            let mut es = GraphEdgeStore::new(&mut self.storage);
            es.incoming_cursor(node_id)?
        };

        loop {
            let record = {
                let mut es = GraphEdgeStore::new(&mut self.storage);
                es.cursor_next_incoming(&mut cursor)?
            };
            match record {
                None => break,
                Some(r) => self.delete_edge(r.edge_id())?,
            }
        }

        let properties = {
            let mut ns = GraphNodeStore::new(&mut self.storage);
            ns.get_node(node_id)?.properties
        };
        self.delete_property_chain(properties)?;
        let mut ns = GraphNodeStore::new(&mut self.storage);
        Ok(ns.delete_node(node_id)?)
    }

    // --- Edges ---

    pub fn insert_edge(
        &mut self,
        src:    u64,
        dst:    u64,
        label:  &str,
        weight: f64,
    ) -> Result<u64, NexoraGraphStoreError> {
        let label_id = {
            let mut ls = LabelStore::new(&mut self.storage);
            ls.insert_label(label.as_bytes())?
        };
        let mut es = GraphEdgeStore::new(&mut self.storage);
        Ok(es.insert_edge(src, dst, label_id, weight)?)
    }

    pub fn get_edge(&mut self, edge_id: u64) -> Result<Edge, NexoraGraphStoreError> {
        let record = {
            let mut es = GraphEdgeStore::new(&mut self.storage);
            es.get_edge(edge_id)?
        };
        let label = self.resolve_label(record.label_id())?;
        Ok(Edge {
            id:     record.edge_id(),
            src:    record.src_node_id(),
            dst:    record.dst_node_id(),
            label,
            weight: record.weight(),
        })
    }

    pub fn update_edge(&mut self, edge: &Edge) -> Result<(), NexoraGraphStoreError> {
        let label_id = {
            let mut ls = LabelStore::new(&mut self.storage);
            ls.insert_label(edge.label.as_bytes())?
        };
        let mut es = GraphEdgeStore::new(&mut self.storage);
        Ok(es.update_label_and_weight(edge.id, label_id, edge.weight)?)
    }

    pub fn delete_edge(&mut self, edge_id: u64) -> Result<(), NexoraGraphStoreError> {
        let properties = {
            let mut es = GraphEdgeStore::new(&mut self.storage);
            es.get_edge(edge_id)?.properties()
        };
        self.delete_property_chain(properties)?;
        let mut es = GraphEdgeStore::new(&mut self.storage);
        Ok(es.delete_edge(edge_id)?)
    }

    // --- Traversal ---

    pub fn outgoing_cursor(&mut self, node_id: u64) -> Result<RecordCursor, NexoraGraphStoreError> {
        let mut es = GraphEdgeStore::new(&mut self.storage);
        Ok(es.outgoing_cursor(node_id)?)
    }

    pub fn incoming_cursor(&mut self, node_id: u64) -> Result<RecordCursor, NexoraGraphStoreError> {
        let mut es = GraphEdgeStore::new(&mut self.storage);
        Ok(es.incoming_cursor(node_id)?)
    }

    pub fn next_outgoing(
        &mut self,
        cursor: &mut RecordCursor,
    ) -> Result<Option<Edge>, NexoraGraphStoreError> {
        let record = {
            let mut es = GraphEdgeStore::new(&mut self.storage);
            es.cursor_next_outgoing(cursor)?
        };
        self.edge_record_to_edge(record)
    }

    pub fn next_incoming(
        &mut self,
        cursor: &mut RecordCursor,
    ) -> Result<Option<Edge>, NexoraGraphStoreError> {
        let record = {
            let mut es = GraphEdgeStore::new(&mut self.storage);
            es.cursor_next_incoming(cursor)?
        };
        self.edge_record_to_edge(record)
    }

    // --- Scan ---

    pub fn all_nodes_cursor(&mut self) -> Result<RecordCursor, NexoraGraphStoreError> {
        let mut ns = GraphNodeStore::new(&mut self.storage);
        Ok(ns.scan_cursor()?)
    }

    pub fn next_node(
        &mut self,
        cursor: &mut RecordCursor,
    ) -> Result<Option<Node>, NexoraGraphStoreError> {
        let record = {
            let mut ns = GraphNodeStore::new(&mut self.storage);
            ns.cursor_next_node(cursor)?
        };
        match record {
            None => Ok(None),
            Some(r) => {
                let label = self.resolve_label(r.label_id.get())?;
                Ok(Some(Node { id: r.node_id.get(), label }))
            }
        }
    }

    pub fn all_edges_cursor(&mut self) -> Result<RecordCursor, NexoraGraphStoreError> {
        let mut es = GraphEdgeStore::new(&mut self.storage);
        Ok(es.scan_cursor()?)
    }

    pub fn next_edge(
        &mut self,
        cursor: &mut RecordCursor,
    ) -> Result<Option<Edge>, NexoraGraphStoreError> {
        let record = {
            let mut es = GraphEdgeStore::new(&mut self.storage);
            es.cursor_next_edge(cursor)?
        };
        self.edge_record_to_edge(record)
    }

    // --- Node properties ---

    pub fn set_node_property(
        &mut self,
        node_id: u64,
        key:     &str,
        value:   &str,
    ) -> Result<(), NexoraGraphStoreError> {
        let node_record = {
            let mut ns = GraphNodeStore::new(&mut self.storage);
            ns.get_node(node_id)?
        };

        // Scan chain for an existing entry with this key — update in place if found.
        let mut ptr = node_record.properties;
        while !ptr.is_null() {
            let prop = {
                let mut ps = PropertyStore::new(&mut self.storage);
                ps.get(ptr)?
            };
            if self.key_matches(prop.key, key)? {
                let new_val = {
                    let mut ss = StringStore::new(&mut self.storage);
                    ss.insert(value.as_bytes())?
                };
                let mut ps = PropertyStore::new(&mut self.storage);
                ps.update_value(ptr, new_val)?;
                return Ok(());
            }
            ptr = prop.next;
        }

        // Key not found — prepend a new property record to the chain.
        let key_ptr = {
            let mut ss = StringStore::new(&mut self.storage);
            ss.insert(key.as_bytes())?
        };
        let val_ptr = {
            let mut ss = StringStore::new(&mut self.storage);
            ss.insert(value.as_bytes())?
        };
        let new_prop_ptr = {
            let mut ps = PropertyStore::new(&mut self.storage);
            ps.insert_chained(key_ptr, val_ptr, node_record.properties)?
        };
        let mut ns = GraphNodeStore::new(&mut self.storage);
        Ok(ns.update_properties(node_id, new_prop_ptr)?)
    }

    pub fn get_node_property(
        &mut self,
        node_id: u64,
        key:     &str,
        out:     &mut [u8],
    ) -> Result<Option<u16>, NexoraGraphStoreError> {
        let node_record = {
            let mut ns = GraphNodeStore::new(&mut self.storage);
            ns.get_node(node_id)?
        };

        let mut ptr = node_record.properties;
        while !ptr.is_null() {
            let prop = {
                let mut ps = PropertyStore::new(&mut self.storage);
                ps.get(ptr)?
            };
            if self.key_matches(prop.key, key)? {
                let len = {
                    let mut ss = StringStore::new(&mut self.storage);
                    ss.get(prop.value, out)?
                };
                return Ok(Some(len));
            }
            ptr = prop.next;
        }

        Ok(None)
    }

    // --- Edge properties ---

    pub fn set_edge_property(
        &mut self,
        edge_id: u64,
        key:     &str,
        value:   &str,
    ) -> Result<(), NexoraGraphStoreError> {
        let edge_record = {
            let mut es = GraphEdgeStore::new(&mut self.storage);
            es.get_edge(edge_id)?
        };

        let mut ptr = edge_record.properties();
        while !ptr.is_null() {
            let prop = {
                let mut ps = PropertyStore::new(&mut self.storage);
                ps.get(ptr)?
            };
            if self.key_matches(prop.key, key)? {
                let new_val = {
                    let mut ss = StringStore::new(&mut self.storage);
                    ss.insert(value.as_bytes())?
                };
                let mut ps = PropertyStore::new(&mut self.storage);
                ps.update_value(ptr, new_val)?;
                return Ok(());
            }
            ptr = prop.next;
        }

        let key_ptr = {
            let mut ss = StringStore::new(&mut self.storage);
            ss.insert(key.as_bytes())?
        };
        let val_ptr = {
            let mut ss = StringStore::new(&mut self.storage);
            ss.insert(value.as_bytes())?
        };
        let new_prop_ptr = {
            let mut ps = PropertyStore::new(&mut self.storage);
            ps.insert_chained(key_ptr, val_ptr, edge_record.properties())?
        };
        let mut es = GraphEdgeStore::new(&mut self.storage);
        Ok(es.update_edge_properties(edge_id, new_prop_ptr)?)
    }

    pub fn get_edge_property(
        &mut self,
        edge_id: u64,
        key:     &str,
        out:     &mut [u8],
    ) -> Result<Option<u16>, NexoraGraphStoreError> {
        let edge_record = {
            let mut es = GraphEdgeStore::new(&mut self.storage);
            es.get_edge(edge_id)?
        };

        let mut ptr = edge_record.properties();
        while !ptr.is_null() {
            let prop = {
                let mut ps = PropertyStore::new(&mut self.storage);
                ps.get(ptr)?
            };
            if self.key_matches(prop.key, key)? {
                let len = {
                    let mut ss = StringStore::new(&mut self.storage);
                    ss.get(prop.value, out)?
                };
                return Ok(Some(len));
            }
            ptr = prop.next;
        }

        Ok(None)
    }

    pub fn node_properties_cursor(
        &mut self,
        node_id: u64,
    ) -> Result<RecordCursor, NexoraGraphStoreError> {
        let node_record = {
            let mut ns = GraphNodeStore::new(&mut self.storage);
            ns.get_node(node_id)?
        };
        Ok(RecordCursor::new(node_record.properties))
    }

    pub fn edge_properties_cursor(
        &mut self,
        edge_id: u64,
    ) -> Result<RecordCursor, NexoraGraphStoreError> {
        let edge_record = {
            let mut es = GraphEdgeStore::new(&mut self.storage);
            es.get_edge(edge_id)?
        };
        Ok(RecordCursor::new(edge_record.properties()))
    }

    pub fn next_property(
        &mut self,
        cursor: &mut RecordCursor,
    ) -> Result<Option<Property>, NexoraGraphStoreError> {
        if cursor.is_done() {
            return Ok(None);
        }
        let prop = {
            let mut ps = PropertyStore::new(&mut self.storage);
            ps.get(cursor.ptr())?
        };
        cursor.advance_to(prop.next);
        let key   = self.resolve_string(prop.key)?;
        let value = self.resolve_string(prop.value)?;
        Ok(Some(Property { key, value }))
    }

    pub fn delete_node_property(
        &mut self,
        node_id: u64,
        key:     &str,
    ) -> Result<bool, NexoraGraphStoreError> {
        let node_record = {
            let mut ns = GraphNodeStore::new(&mut self.storage);
            ns.get_node(node_id)?
        };

        let mut prev_ptr = PackedPtr::NULL;
        let mut curr_ptr = node_record.properties;

        while !curr_ptr.is_null() {
            let prop = {
                let mut ps = PropertyStore::new(&mut self.storage);
                ps.get(curr_ptr)?
            };
            if self.key_matches(prop.key, key)? {
                if prev_ptr.is_null() {
                    let mut ns = GraphNodeStore::new(&mut self.storage);
                    ns.update_properties(node_id, prop.next)?;
                } else {
                    let mut ps = PropertyStore::new(&mut self.storage);
                    ps.update_next(prev_ptr, prop.next)?;
                }
                {
                    let mut ss = StringStore::new(&mut self.storage);
                    ss.delete(prop.key)?;
                }
                {
                    let mut ss = StringStore::new(&mut self.storage);
                    ss.delete(prop.value)?;
                }
                let mut ps = PropertyStore::new(&mut self.storage);
                ps.delete(curr_ptr)?;
                return Ok(true);
            }
            prev_ptr = curr_ptr;
            curr_ptr = prop.next;
        }

        Ok(false)
    }

    pub fn delete_edge_property(
        &mut self,
        edge_id: u64,
        key:     &str,
    ) -> Result<bool, NexoraGraphStoreError> {
        let edge_record = {
            let mut es = GraphEdgeStore::new(&mut self.storage);
            es.get_edge(edge_id)?
        };

        let mut prev_ptr = PackedPtr::NULL;
        let mut curr_ptr = edge_record.properties();

        while !curr_ptr.is_null() {
            let prop = {
                let mut ps = PropertyStore::new(&mut self.storage);
                ps.get(curr_ptr)?
            };
            if self.key_matches(prop.key, key)? {
                if prev_ptr.is_null() {
                    let mut es = GraphEdgeStore::new(&mut self.storage);
                    es.update_edge_properties(edge_id, prop.next)?;
                } else {
                    let mut ps = PropertyStore::new(&mut self.storage);
                    ps.update_next(prev_ptr, prop.next)?;
                }
                {
                    let mut ss = StringStore::new(&mut self.storage);
                    ss.delete(prop.key)?;
                }
                {
                    let mut ss = StringStore::new(&mut self.storage);
                    ss.delete(prop.value)?;
                }
                let mut ps = PropertyStore::new(&mut self.storage);
                ps.delete(curr_ptr)?;
                return Ok(true);
            }
            prev_ptr = curr_ptr;
            curr_ptr = prop.next;
        }

        Ok(false)
    }

    // --- Private helpers ---

    fn delete_property_chain(&mut self, head: PackedPtr) -> Result<(), NexoraGraphStoreError> {
        let mut ptr = head;
        while !ptr.is_null() {
            let prop = {
                let mut ps = PropertyStore::new(&mut self.storage);
                ps.get(ptr)?
            };
            let next = prop.next;
            {
                let mut ss = StringStore::new(&mut self.storage);
                ss.delete(prop.key)?;
            }
            {
                let mut ss = StringStore::new(&mut self.storage);
                ss.delete(prop.value)?;
            }
            {
                let mut ps = PropertyStore::new(&mut self.storage);
                ps.delete(ptr)?;
            }
            ptr = next;
        }
        Ok(())
    }

    fn key_matches(&mut self, key_ptr: PackedPtr, key: &str) -> Result<bool, NexoraGraphStoreError> {
        let mut buf = [0u8; MAX_LABEL_LENGTH];
        let len = {
            let mut ss = StringStore::new(&mut self.storage);
            ss.get(key_ptr, &mut buf)?
        };
        Ok(&buf[..len as usize] == key.as_bytes())
    }

    fn resolve_string(&mut self, ptr: PackedPtr) -> Result<String, NexoraGraphStoreError> {
        // TODO(phase3): allocates up to MAX_STRING_LENGTH bytes per call. Once the buffer pool
        // pins pages in memory, return a &str borrowed from the cached page — zero allocation.
        let mut buf = vec![0u8; MAX_STRING_LENGTH];
        let len = {
            let mut ss = StringStore::new(&mut self.storage);
            ss.get(ptr, &mut buf)?
        };
        String::from_utf8(buf[..len as usize].to_vec())
            .map_err(|_| NexoraGraphStoreError::InvalidUtf8)
    }

    fn resolve_label(&mut self, label_id: u32) -> Result<String, NexoraGraphStoreError> {
        // TODO(phase3): This allocates a String (heap) on every label read. Once the buffer pool
        // is in place, pages are pinned in memory and we can return a &str borrowed directly from
        // the cached page — zero allocation. Until then, the caller-provides-buffer pattern
        // (get_node_label) is the zero-allocation path; this convenience method always allocates.
        let mut buf = [0u8; MAX_LABEL_LENGTH];
        let len = {
            let mut ls = LabelStore::new(&mut self.storage);
            ls.get_label(label_id, &mut buf)?
        };
        String::from_utf8(buf[..len as usize].to_vec())
            .map_err(|_| NexoraGraphStoreError::InvalidUtf8)
    }

    fn edge_record_to_edge(
        &mut self,
        record: Option<GraphEdgeRecord>,
    ) -> Result<Option<Edge>, NexoraGraphStoreError> {
        match record {
            None => Ok(None),
            Some(r) => {
                let label = self.resolve_label(r.label_id())?;
                Ok(Some(Edge {
                    id:     r.edge_id(),
                    src:    r.src_node_id(),
                    dst:    r.dst_node_id(),
                    label,
                    weight: r.weight(),
                }))
            }
        }
    }
}


impl GraphStore<crate::storage::page_store_disk::RegularPageStore> {
    pub fn create(path: &std::path::Path) -> Result<Self, NexoraGraphStoreError> {
        let store = crate::storage::page_store_disk::RegularPageStore::create(path)?;
        let storage = StorageManager::from_page_store(store)?;
        Ok(GraphStore::new(storage))
    }

    pub fn open(path: &std::path::Path) -> Result<Self, NexoraGraphStoreError> {
        let store = crate::storage::page_store_disk::RegularPageStore::open(path)?;
        let storage = StorageManager::from_page_store(store)?;
        Ok(GraphStore::new(storage))
    }
}
