// AI_GENERATED: Generated by AI (CLAUDE_CODE)
#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use crate::graph::edge::error::NexoraGraphEdgeError;
    use crate::graph::edge::graph_edge_store::GraphEdgeStore;
    use crate::graph::edge::constants::MAX_EDGE_RECORD_COUNT;
    use crate::graph::node::graph_node_store::GraphNodeStore;
    use crate::storage::page_store_disk::RegularPageStore;
    use crate::storage::storage_manager::StorageManager;

    fn tmp_path(name: &str) -> PathBuf {
        std::env::temp_dir().join(name)
    }

    fn cleanup(path: &PathBuf) {
        let _ = std::fs::remove_file(path);
    }

    fn setup(path: &PathBuf) -> StorageManager<RegularPageStore> {
        let store = RegularPageStore::create(path).unwrap();
        StorageManager::from_page_store(store).unwrap()
    }

    fn insert_nodes(manager: &mut StorageManager<RegularPageStore>, count: usize) -> Vec<u64> {
        let mut node_store = GraphNodeStore::new(manager);
        (0..count).map(|_| node_store.insert_node(1, 0, 0).unwrap()).collect()
    }

    // Test 1 — basic insert and get round trip
    #[test]
    fn test_insert_and_get_edge() {
        let path = tmp_path("test_edge_insert_get.nxra");
        cleanup(&path);
        let mut manager = setup(&path);

        let nodes = insert_nodes(&mut manager, 2);
        let mut edge_store = GraphEdgeStore::new(&mut manager);

        let edge_id = edge_store.insert_edge(nodes[0], nodes[1], 1, 1.0).unwrap();
        let record = edge_store.get_edge(edge_id).unwrap();

        assert_eq!(record.edge_id(), edge_id);
        assert_eq!(record.src_node_id(), nodes[0]);
        assert_eq!(record.dst_node_id(), nodes[1]);
        assert_eq!(record.weight(), 1.0);

        cleanup(&path);
    }

    // Test 2 — get a nonexistent edge
    #[test]
    fn test_get_nonexistent_edge() {
        let path = tmp_path("test_edge_get_nonexistent.nxra");
        cleanup(&path);
        let mut manager = setup(&path);

        insert_nodes(&mut manager, 2);
        let mut edge_store = GraphEdgeStore::new(&mut manager);

        assert!(matches!(edge_store.get_edge(999), Err(NexoraGraphEdgeError::EdgeNotFound)));

        cleanup(&path);
    }

    // Test 3 — insert edge referencing a nonexistent node
    #[test]
    fn test_insert_edge_missing_node() {
        let path = tmp_path("test_edge_missing_node.nxra");
        cleanup(&path);
        let mut manager = setup(&path);

        insert_nodes(&mut manager, 1);
        let mut edge_store = GraphEdgeStore::new(&mut manager);

        assert!(matches!(edge_store.insert_edge(0, 999, 1, 1.0), Err(NexoraGraphEdgeError::NodeNotFound)));

        cleanup(&path);
    }

    // Test 4 — delete an edge then get returns EdgeNotFound
    #[test]
    fn test_delete_edge() {
        let path = tmp_path("test_edge_delete.nxra");
        cleanup(&path);
        let mut manager = setup(&path);

        let nodes = insert_nodes(&mut manager, 2);
        let mut edge_store = GraphEdgeStore::new(&mut manager);

        let edge_id = edge_store.insert_edge(nodes[0], nodes[1], 1, 1.0).unwrap();
        edge_store.delete_edge(edge_id).unwrap();

        assert!(matches!(edge_store.get_edge(edge_id), Err(NexoraGraphEdgeError::EdgeNotFound)));

        cleanup(&path);
    }

    // Test 5 — delete a nonexistent edge
    #[test]
    fn test_delete_nonexistent_edge() {
        let path = tmp_path("test_edge_delete_nonexistent.nxra");
        cleanup(&path);
        let mut manager = setup(&path);

        insert_nodes(&mut manager, 2);
        let mut edge_store = GraphEdgeStore::new(&mut manager);

        assert!(matches!(edge_store.delete_edge(999), Err(NexoraGraphEdgeError::EdgeNotFound)));

        cleanup(&path);
    }

    // Test 6 — outgoing cursor visits all inserted edges from a node
    #[test]
    fn test_outgoing_edges() {
        let path = tmp_path("test_edge_outgoing.nxra");
        cleanup(&path);
        let mut manager = setup(&path);

        let nodes = insert_nodes(&mut manager, 3);
        let mut edge_store = GraphEdgeStore::new(&mut manager);

        let e1 = edge_store.insert_edge(nodes[0], nodes[1], 1, 1.0).unwrap();
        let e2 = edge_store.insert_edge(nodes[0], nodes[2], 1, 2.0).unwrap();

        let mut cursor = edge_store.outgoing_cursor(nodes[0]).unwrap();
        let mut ids = [0u64; 2];
        let mut count = 0;
        while let Some(edge) = edge_store.cursor_next_outgoing(&mut cursor).unwrap() {
            ids[count] = edge.edge_id();
            count += 1;
        }

        assert_eq!(count, 2);
        assert!(ids.contains(&e1));
        assert!(ids.contains(&e2));

        cleanup(&path);
    }

    // Test 7 — incoming cursor visits all inserted edges to a node
    #[test]
    fn test_incoming_edges() {
        let path = tmp_path("test_edge_incoming.nxra");
        cleanup(&path);
        let mut manager = setup(&path);

        let nodes = insert_nodes(&mut manager, 3);
        let mut edge_store = GraphEdgeStore::new(&mut manager);

        let e1 = edge_store.insert_edge(nodes[0], nodes[2], 1, 1.0).unwrap();
        let e2 = edge_store.insert_edge(nodes[1], nodes[2], 1, 2.0).unwrap();

        let mut cursor = edge_store.incoming_cursor(nodes[2]).unwrap();
        let mut ids = [0u64; 2];
        let mut count = 0;
        while let Some(edge) = edge_store.cursor_next_incoming(&mut cursor).unwrap() {
            ids[count] = edge.edge_id();
            count += 1;
        }

        assert_eq!(count, 2);
        assert!(ids.contains(&e1));
        assert!(ids.contains(&e2));

        cleanup(&path);
    }

    // Test 8 — delete middle edge, chain remains intact
    #[test]
    fn test_delete_middle_edge_chain_intact() {
        let path = tmp_path("test_edge_delete_middle.nxra");
        cleanup(&path);
        let mut manager = setup(&path);

        let nodes = insert_nodes(&mut manager, 3);
        let mut edge_store = GraphEdgeStore::new(&mut manager);

        let e1 = edge_store.insert_edge(nodes[0], nodes[1], 1, 1.0).unwrap();
        let e2 = edge_store.insert_edge(nodes[0], nodes[2], 1, 2.0).unwrap();
        let e3 = edge_store.insert_edge(nodes[0], nodes[1], 1, 3.0).unwrap();

        edge_store.delete_edge(e2).unwrap();

        let mut cursor = edge_store.outgoing_cursor(nodes[0]).unwrap();
        let mut ids = [0u64; 2];
        let mut count = 0;
        while let Some(edge) = edge_store.cursor_next_outgoing(&mut cursor).unwrap() {
            ids[count] = edge.edge_id();
            count += 1;
        }

        assert_eq!(count, 2);
        assert!(ids.contains(&e1));
        assert!(ids.contains(&e3));
        assert!(!ids.contains(&e2));

        cleanup(&path);
    }

    // Test 9 — edge count tracked in footer
    #[test]
    fn test_edge_count_tracking() {
        let path = tmp_path("test_edge_count.nxra");
        cleanup(&path);
        let mut manager = setup(&path);

        let nodes = insert_nodes(&mut manager, 2);

        let edge_id = {
            let mut edge_store = GraphEdgeStore::new(&mut manager);
            edge_store.insert_edge(nodes[0], nodes[1], 1, 1.0).unwrap();
            edge_store.insert_edge(nodes[0], nodes[1], 1, 2.0).unwrap();
            edge_store.insert_edge(nodes[0], nodes[1], 1, 3.0).unwrap()
        };

        assert_eq!(manager.footer.edge_count.get(), 3);

        {
            let mut edge_store = GraphEdgeStore::new(&mut manager);
            edge_store.delete_edge(edge_id).unwrap();
        }

        assert_eq!(manager.footer.edge_count.get(), 2);

        cleanup(&path);
    }

    // Test 10 — self-loop (src == dst)
    #[test]
    fn test_self_loop() {
        let path = tmp_path("test_edge_self_loop.nxra");
        cleanup(&path);
        let mut manager = setup(&path);

        let nodes = insert_nodes(&mut manager, 1);
        let mut edge_store = GraphEdgeStore::new(&mut manager);

        let edge_id = edge_store.insert_edge(nodes[0], nodes[0], 1, 0.5).unwrap();
        let record = edge_store.get_edge(edge_id).unwrap();

        assert_eq!(record.src_node_id(), nodes[0]);
        assert_eq!(record.dst_node_id(), nodes[0]);

        cleanup(&path);
    }

    // Test 11 — edges survive close and reopen
    #[test]
    fn test_edge_persistence() {
        let path = tmp_path("test_edge_persistence.nxra");
        cleanup(&path);

        let edge_id = {
            let mut manager = setup(&path);
            let nodes = insert_nodes(&mut manager, 2);
            let edge_id = {
                let mut edge_store = GraphEdgeStore::new(&mut manager);
                edge_store.insert_edge(nodes[0], nodes[1], 1, 42.0).unwrap()
            };
            manager.close().unwrap();
            edge_id
        };

        {
            let store = RegularPageStore::open(&path).unwrap();
            let mut manager = StorageManager::from_page_store(store).unwrap();
            let mut edge_store = GraphEdgeStore::new(&mut manager);
            let record = edge_store.get_edge(edge_id).unwrap();
            assert_eq!(record.edge_id(), edge_id);
            assert_eq!(record.weight(), 42.0);
        }

        cleanup(&path);
    }

    // Test 12 — insert beyond MAX_EDGE_RECORD_COUNT triggers new page
    #[test]
    fn test_edge_page_overflow() {
        let path = tmp_path("test_edge_page_overflow.nxra");
        cleanup(&path);
        let mut manager = setup(&path);

        let nodes = insert_nodes(&mut manager, 2);
        let mut edge_store = GraphEdgeStore::new(&mut manager);

        let ids: Vec<u64> = (0..MAX_EDGE_RECORD_COUNT + 5)
            .map(|_| edge_store.insert_edge(nodes[0], nodes[1], 1, 1.0).unwrap())
            .collect();

        for id in &ids {
            assert_eq!(edge_store.get_edge(*id).unwrap().edge_id(), *id);
        }

        cleanup(&path);
    }
}
